<a href="https://colab.research.google.com/github/Swapnika29/balagopi/blob/main/DATA602_PSC2_HW1_Fall2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **HOMEWORK 2: PANDAS and SQL (TOTAL 80)**
## **DUE: *SEPTEMBER 26, 2024 @ 11:59 PM***

---------------------
#### **DATASET DESCRIPTION**

The [NCEI/WDS Global Significant Volcanic Eruptions Database](https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.ngdc.mgg.hazards:G10147) is a very comprehensive collection of +600 volcanic eruptions dating from 4360 BC to the present. Due to the nature of this assignment, we will be dealing with relatively newer volcanoes (in which some are still obviously still older than anyone on Earth currently). Each eruption in the database is classified as significant if it meets one or more criteria, such as causing fatalities, incurring **damage on property** (**+$1 million**), reaching a **Volcanic Explosivity Index (VEI)** of **6 or higher**, generating a tsunami, or being linked to a significant earthquake. The VEI is a scale that measures the explosiveness of volcanic eruptions, providing insight into the magnitude and potential consequences of the eruptions. The database includes detailed information on the location, type of volcano, last known eruption, VEI, casualties, property damage, and much more.
![volcano](https://wikitravel.org/upload/shared//9/99/Volcano_de_Fuego_Banner.jpg)

#### **Objective of the Assignment:**


We will proceed directly to exploring these volcanic datasets, with the aim of enhancing our proficiency in Pandas and SQL.

For your reference, the [Pandas Documentation](https://pandas.pydata.org/docs/user_guide/index.html) will be an invaluable resource. Additionally, we have provided several helpful links to assist you throughout this process. Please proceed with caution to avoid any potential pitf

---------------------

### **DO NOT REMOVE ANY PART OF ANY OF THE QUESTIONS OR YOU LOSE CREDIT**
### *No Hardcoding either*  
### **REMEMBER TO SHOW ALL CODE OUTPUT (NO CREDIT OTHERWISE)**

### **Part 1: Maintenance  (25 POINTS TOTAL)**

First, in this section, we will focus on the initial steps of the process.

As is standard practice in Python programming, it is best to import necessary modules at the beginning of your script before writing any additional code. This approach ensures that all required libraries are available from the start.

In [52]:
# Make sure these code blocks run properly and that you have properly installed the appropriate modules required.
import pandas as pd
import requests
from bs4 import BeautifulSoup

# import other libraries here

# Don't remove this
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

As you may have noticed, there is an additional library, apart from Pandas, called "[requests](https://requests.readthedocs.io/en/latest/)."

**The requests library enables you to send HTTP requests to a server, retrieve content, and process it with ease.**  It is particularly user-friendly for beginners venturing into web scraping, which is crucial for collecting and constructing datasets. Additionally, we recommend exploring [BeautifulSoup](https://beautiful-soup-4.readthedocs.io/en/latest/), , a complementary library that can be used alongside requests for more efficient web scraping.

* As shown below, sometimes specific websites require specific headers in order to process a request to access the data.

* To check if a request was processed successfully, use the [status_code](https://requests.readthedocs.io/en/latest/api/) function to see if the process returned 200.

In [53]:
# API URL and headers in case request gets denied.
api_url = "https://www.ngdc.noaa.gov/hazel/hazard-service/api/v1/volcanoes"

headers = {
    'accept': '*/*'
}

#### **TASK 1.0: Webscraping (5 points)**

To develop our web scraper, we need to **initiate a GET request** a GET request using the relevant information provided above.

This specific NOAA dataset API returns data in JSON format when a request is made. The JSON data is structured in a particular format, so we will extract the necessary information solely from the field named "items" to construct a DataFrame.

**After successfully scraping the data, name the resulting DataFrame** ***df***

**Subsequently, save this DataFrame to a CSV file named volcanoes.csv.**

**This process should only need to be executed once.**

In [54]:
#Initiating a GET request
initiatingrequest = requests.get(api_url, headers=headers)

#Checking Whether the request processed successfully
if initiatingrequest.status_code == 200:
    print("Request successful")

#Parsing the data which is in JSON Format
data = initiatingrequest.json()

#Extracting the information from the field named "items" to construct a DataFrame
items = data.get('items', [])

#Creating the resulting DataFrame df
df = pd.DataFrame(items)

#saving this DataFrame to a CSV file named volcanoes.csv.
df.to_csv('volcanoes.csv', index=False)

Request successful

#### **TASK 1.1: 1-Liner Overview (3 points)**
To gain an understanding of the dataset's structure, we need to examine some fundamental characteristics of the DataFrame. We need to get an idea of what this dataset is going to look. In order to do that, let's take a look at some of the most [basic things](https://dataanalytics.buffalostate.edu/pandas-cheat-sheet) our dataframe has.


***CAN'T USE LOOPS. DO NOT DISPLAY THE DATAFRAME, JUST YOUR CODE OUTPUT HERE.***

**1.1.1:** *In one line of code and **using only one function**, show how many **total datapoints and features** there are in the dataframe **together**.*

In [55]:
print(df.size)
df.shape

8600

(200, 43)

**1.1.2:** *In one line of code, list the **names** of all the **features** in the dataframe.*

In [56]:
df.columns.tolist()

['id',
 'year',
 'month',
 'day',
 'tsunamiEventId',
 'earthquakeEventId',
 'volcanoLocationId',
 'volcanoLocationNewNum',
 'volcanoLocationNum',
 'name',
 'location',
 'country',
 'latitude',
 'longitude',
 'elevation',
 'morphology',
 'agent',
 'deathsTotal',
 'deathsAmountOrderTotal',
 'damageAmountOrderTotal',
 'significant',
 'publish',
 'eruption',
 'status',
 'timeErupt',
 'vei',
 'deathsAmountOrder',
 'damageAmountOrder',
 'housesDestroyedAmountOrderTotal',
 'deaths',
 'injuries',
 'injuriesAmountOrder',
 'injuriesTotal',
 'injuriesAmountOrderTotal',
 'housesDestroyedAmountOrder',
 'housesDestroyed',
 'housesDestroyedTotal',
 'missingAmountOrder',
 'missingAmountOrderTotal',
 'missing',
 'missingTotal',
 'damageMillionsDollars',
 'damageMillionsDollarsTotal']

We won't be using some of the data because there is a lot of missing data.

**1.1.3:** *In one line of code, create a **new dataframe** called **new_df** that **contains all** the features of the **old** dataframe **except the following**:*

volcanoLocationNum, location, latitude, longitude, agent, significant,	publish,	eruption,	status, timeErupt, damageAmountOrder, damageAmountOrderTotal, housesDestroyedAmountOrder,	housesDestroyedAmountOrderTotal, housesDestroyed,	housesDestroyedTotal,	missingAmountOrder,	missingAmountOrderTotal,	missing,	missingTotal, damageMillionsDollars, damageMillionsDollarsTotal, injuries, injuriesAmountOrder, injuriesTotal, injuriesAmountOrderTotal, deathsAmountOrderTotal, and deathsAmountOrder.

In [57]:
new_df = df.drop(['volcanoLocationNum', 'location', 'latitude', 'longitude', 'agent', 'significant', 'publish', 'eruption', 'status', 'timeErupt', 'damageAmountOrder', 'damageAmountOrderTotal', 'housesDestroyedAmountOrder', 'housesDestroyedAmountOrderTotal', 'housesDestroyed', 'housesDestroyedTotal', 'missingAmountOrder', 'missingAmountOrderTotal', 'missing', 'missingTotal', 'damageMillionsDollars', 'damageMillionsDollarsTotal', 'injuries', 'injuriesAmountOrder', 'injuriesTotal', 'injuriesAmountOrderTotal', 'deathsAmountOrderTotal', 'deathsAmountOrder'], axis=1)

# KEEP THIS. It will display the whole dataframe.
new_df

,id,year,month,day,tsunamiEventId,earthquakeEventId,volcanoLocationId,volcanoLocationNewNum,name,country,elevation,morphology,deathsTotal,vei,deaths
0,1,1169,2.0,4.0,2852.0,421.0,10106,211060,Etna,Italy,3357,Stratovolcano,16000.0,NaN,NaN
1,2,1329,7.0,NaN,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,NaN,1.0,NaN
2,3,1883,3.0,NaN,NaN,NaN,30301,233010,Karthala,Comoros,2361,Shield volcano,NaN,2.0,NaN
3,4,1888,3.0,13.0,1175.0,NaN,50107,251070,Ritter Island,Papua New Guinea,75,Stratovolcano,NaN,2.0,NaN
4,5,1850,NaN,NaN,NaN,NaN,50214,252140,Rabaul,Papua New Guinea,688,Pyroclastic shield,NaN,2.0,NaN
5,6,1832,11.0,1.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,NaN,2.0,NaN
6,7,1977,1.0,10.0,NaN,NaN,20303,223030,Nyiragongo,"Congo, DRC",3470,Stratovolcano,NaN,1.0,NaN
7,8,787,NaN,NaN,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,NaN,3.0,NaN
8,9,1779,8.0,8.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,NaN,2.0,NaN
9,10,1302,NaN,NaN,NaN,NaN,10103,211030,Ischia,Italy,789,Complex volcano,NaN,NaN,NaN
10,11,1907,8.0,4.0,NaN,NaN,201112,221112,Alayta,Ethiopia,1496,Shield volcano,NaN,2.0,NaN
11,12,1905,3.0,10.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,1.0,2.0,1.0
12,13,1986,7.0,24.0,NaN,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,1.0,2.0,1.0
13,14,1536,3.0,23.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,1.0,3.0,1.0
14,15,1904,2.0,25.0,NaN,NaN,30301,233010,Karthala,Comoros,2361,Shield volcano,1.0,2.0,1.0
15,16,1878,1.0,NaN,1095.0,6195.0,50214,252140,Rabaul,Papua New Guinea,688,Pyroclastic shield,1.0,3.0,1.0
16,17,1737,5.0,20.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,2.0,2.0,2.0
17,18,1917,4.0,1.0,NaN,NaN,40105,241050,Okataina,New Zealand,1111,Lava dome,2.0,1.0,2.0
18,19,1899,NaN,NaN,NaN,NaN,50102,251020,Manam,Papua New Guinea,1807,Stratovolcano,2.0,2.0,2.0
19,20,1979,3.0,8.0,NaN,NaN,50103,251030,Karkar,Papua New Guinea,1839,Stratovolcano,2.0,2.0,2.0
20,21,1970,3.0,2.0,NaN,NaN,10101,211010,Campi Flegrei,Italy,458,Caldera,3.0,NaN,3.0
21,22,1972,6.0,9.0,NaN,NaN,30302,233020,"Fournaise, Piton de la",Reunion,2632,Shield volcano,3.0,2.0,3.0
22,23,1682,8.0,12.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,4.0,3.0,4.0
23,24,1805,8.0,11.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,4.0,2.0,4.0
24,25,1919,5.0,22.0,1476.0,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,4.0,3.0,4.0
25,26,1930,9.0,11.0,4218.0,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,6.0,3.0,5.0
26,27,1903,8.0,30.0,NaN,NaN,40105,241050,Okataina,New Zealand,1111,Lava dome,4.0,1.0,4.0
27,28,1928,11.0,2.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,5.0,1.0,5.0
28,29,1872,4.0,24.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,9.0,3.0,9.0
29,30,1979,7.0,5.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,9.0,2.0,9.0
30,31,1987,4.0,17.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,2.0,2.0,2.0
31,32,1914,9.0,10.0,NaN,NaN,40104,241040,Whakaari/White Island,New Zealand,294,Stratovolcano,11.0,NaN,11.0
32,33,1886,8.0,31.0,NaN,NaN,40311,243110,Niuafo'ou,Tonga,260,Shield volcano,NaN,4.0,NaN
33,34,1912,12.0,3.0,NaN,NaN,20302,223020,Nyamulagira,"Congo, DRC",3058,Shield volcano,20.0,3.0,20.0
34,35,1895,6.0,17.0,NaN,NaN,50103,251030,Karkar,Papua New Guinea,1839,Stratovolcano,21.0,2.0,1.0
35,36,1538,9.0,29.0,NaN,NaN,10101,211010,Campi Flegrei,Italy,458,Caldera,24.0,3.0,24.0
36,37,1853,6.0,24.0,NaN,NaN,40311,243110,Niuafo'ou,Tonga,260,Shield volcano,25.0,0.0,25.0
37,38,1954,8.0,3.0,NaN,NaN,50101,251010,Bam,Papua New Guinea,685,Stratovolcano,25.0,2.0,NaN
38,39,1944,3.0,27.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,27.0,2.0,27.0
39,40,1984,8.0,15.0,5807.0,NaN,20403,224030,Oku Volcanic Field,Cameroon,3011,Maar,37.0,NaN,37.0
40,41,-141,NaN,NaN,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,40.0,NaN,40.0
41,42,1928,1.0,23.0,NaN,NaN,10204,212040,Santorini,Greece,367,Shield volcano,48.0,2.0,48.0
42,43,1631,2.0,14.0,NaN,920.0,201141,221141,Dama Ali,Ethiopia,1068,Shield volcano,50.0,NaN,50.0
43,44,1843,11.0,17.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,56.0,2.0,56.0
44,45,1944,12.0,4.0,NaN,NaN,60320,263200,Dieng Volcanic Complex,Indonesia,2565,Complex volcano,117.0,2.0,117.0
45,49,1979,2.0,20.0,NaN,NaN,60320,263200,Dieng Volcanic Complex,Indonesia,2565,Complex volcano,149.0,1.0,149.0
46,61,1587,NaN,NaN,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,NaN,4.0,NaN
47,64,1672,8.0,4.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,3000.0,3.0,3000.0
48,69,1822,12.0,27.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,100.0,3.0,100.0
49,71,1832,12.0,25.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,32.0,3.0,32.0
50,81,1872,4.0,15.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,30.0,4.0,30.0
51,82,1872,11.0,3.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,200.0,4.0,200.0
52,87,1902,12.0,NaN,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,16.0,2.0,16.0
53,92,1920,7.0,25.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,33.0,3.0,33.0
54,94,1930,12.0,18.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,1369.0,3.0,1369.0
55,100,1953,3.0,23.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,64.0,3.0,64.0
56,104,1961,5.0,8.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,6.0,3.0,6.0
57,105,1969,1.0,7.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,3.0,2.0,3.0
58,111,1986,10.0,15.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,1.0,2.0,1.0
59,112,1994,11.0,22.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,60.0,3.0,60.0
60,116,1311,NaN,NaN,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN
61,117,1334,NaN,NaN,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN
62,118,1376,NaN,NaN,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN
63,119,1385,NaN,NaN,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN
64,126,1586,NaN,NaN,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,10000.0,5.0,10000.0
65,128,1716,7.0,20.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,2.0,NaN
66,132,1826,10.0,11.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN
67,133,1848,5.0,16.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,21.0,2.0,21.0
68,135,1864,1.0,3.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,54.0,2.0,54.0
69,136,1875,1.0,29.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,0.0,NaN
70,137,1901,5.0,22.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN
71,138,1919,5.0,19.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,5110.0,4.0,5110.0
72,140,1951,8.0,31.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,7.0,3.0,7.0
73,141,1966,4.0,26.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,215.0,4.0,215.0
74,144,1990,2.0,10.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,32.0,4.0,32.0
75,159,1860,4.0,NaN,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN
76,167,1885,4.0,18.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,74.0,2.0,74.0
77,176,1895,5.0,22.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN
78,191,1909,9.0,NaN,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,221.0,2.0,221.0
79,193,1911,11.0,8.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,3.0,NaN
80,195,1913,6.0,23.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN
81,196,1941,9.0,21.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN
82,198,1946,2.0,NaN,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,6.0,2.0,6.0
83,199,1946,10.0,29.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN
84,200,1950,8.0,28.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,6.0,1.0,6.0
85,201,1963,5.0,5.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,1.0,2.0,1.0
86,202,1967,8.0,31.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,3.0,3.0,3.0
87,203,1985,5.0,10.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,70.0,3.0,70.0
88,204,1978,9.0,19.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,12.0,3.0,12.0
89,205,1976,8.0,31.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,119.0,2.0,119.0
90,206,1981,3.0,29.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,1.0,3.0,1.0
91,261,1843,8.0,NaN,NaN,NaN,60332,263320,Lamongan,Indonesia,1641,Stratovolcano,4.0,2.0,4.0
92,269,1869,8.0,NaN,NaN,NaN,60332,263320,Lamongan,Indonesia,1641,Stratovolcano,8.0,2.0,8.0
93,294,1593,NaN,NaN,NaN,NaN,60334,263340,Raung,Indonesia,3260,Stratovolcano,NaN,5.0,NaN
94,295,1597,NaN,NaN,NaN,NaN,60334,263340,Raung,Indonesia,3260,Stratovolcano,NaN,3.0,NaN
95,296,1638,NaN,NaN,NaN,NaN,60334,263340,Raung,Indonesia,3260,Stratovolcano,1001.0,4.0,1001.0
96,297,1730,NaN,NaN,NaN,NaN,60334,263340,Raung,Indonesia,3260,Stratovolcano,NaN,3.0,NaN
97,298,1817,NaN,NaN,NaN,NaN,60334,263340,Raung,Indonesia,3260,Stratovolcano,NaN,4.0,NaN
98,333,1817,1.0,24.0,NaN,NaN,60335,263350,Ijen,Indonesia,2769,Stratovolcano,NaN,2.0,NaN
99,345,1963,9.0,5.0,NaN,NaN,60401,264010,Batur,Indonesia,1717,Caldera,2.0,2.0,2.0
100,351,1963,3.0,18.0,1942.0,NaN,60402,264020,Agung,Indonesia,2997,Stratovolcano,1028.0,5.0,1028.0
101,353,1963,5.0,16.0,NaN,4292.0,60402,264020,Agung,Indonesia,2997,Stratovolcano,120.0,3.0,120.0
102,367,1815,4.0,10.0,613.0,NaN,60404,264040,Tambora,Indonesia,2850,Stratovolcano,60000.0,7.0,11000.0
103,389,1969,1.0,28.0,NaN,NaN,60411,264110,Iya,Indonesia,618,Stratovolcano,2.0,3.0,2.0
104,394,1928,8.0,4.0,1607.0,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,226.0,3.0,98.0
105,395,1964,1.0,1.0,NaN,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,1.0,2.0,1.0
106,397,1973,1.0,NaN,NaN,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,NaN,3.0,NaN
107,398,1981,9.0,5.0,NaN,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,NaN,2.0,NaN
108,410,1869,7.0,7.0,NaN,NaN,60418,264180,Lewotobi,Indonesia,1703,Stratovolcano,2.0,2.0,2.0
109,411,1907,9.0,28.0,NaN,NaN,60418,264180,Lewotobi,Indonesia,1703,Stratovolcano,1.0,2.0,1.0
110,439,1870,NaN,NaN,NaN,NaN,60425,264250,Iliwerung,Indonesia,583,Complex volcano,NaN,3.0,NaN
111,441,1948,4.0,7.0,NaN,NaN,60425,264250,Iliwerung,Indonesia,583,Complex volcano,NaN,2.0,NaN
112,445,1973,12.0,NaN,5761.0,NaN,60425,264250,Iliwerung,Indonesia,583,Complex volcano,2.0,2.0,NaN
113,447,1983,8.0,17.0,4702.0,NaN,60425,264250,Iliwerung,Indonesia,583,Complex volcano,NaN,1.0,NaN
114,450,1953,6.0,NaN,NaN,NaN,60427,264270,Sirung,Indonesia,862,Complex volcano,5.0,0.0,5.0
115,457,1659,11.0,11.0,285.0,NaN,60505,265050,Teon,Pacific Ocean,728,Stratovolcano,NaN,4.0,NaN
116,458,1660,2.0,NaN,NaN,NaN,60505,265050,Teon,Pacific Ocean,728,Stratovolcano,3.0,4.0,3.0
117,466,1692,6.0,4.0,NaN,NaN,60507,265070,Serua,Pacific Ocean,608,Stratovolcano,NaN,4.0,NaN
118,472,1598,NaN,NaN,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,NaN,3.0,NaN
119,474,1615,3.0,NaN,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,NaN,3.0,NaN
120,477,1694,11.0,20.0,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,NaN,3.0,NaN
121,482,1820,6.0,11.0,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,NaN,2.0,NaN
122,486,1988,5.0,9.0,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,4.0,3.0,4.0
123,488,1983,7.0,23.0,NaN,NaN,60601,266010,Colo,Indonesia,404,Stratovolcano,NaN,4.0,NaN
124,489,1845,2.0,8.0,741.0,1865.0,60603,266030,Soputan,Indonesia,1785,Stratovolcano,118.0,2.0,NaN
125,525,1958,7.0,12.0,NaN,NaN,60611,266110,Mahawu,Indonesia,1299,Stratovolcano,1.0,2.0,1.0
126,530,1870,8.0,NaN,NaN,NaN,60701,267010,Ruang,Indonesia,725,Stratovolcano,NaN,2.0,NaN
127,533,1871,3.0,3.0,1022.0,NaN,60701,267010,Ruang,Indonesia,725,Stratovolcano,400.0,2.0,NaN
128,552,1940,6.0,20.0,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,1.0,2.0,1.0
129,561,1974,2.0,11.0,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,4.0,3.0,4.0
130,562,1976,9.0,15.0,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,1.0,2.0,1.0
131,569,1889,9.0,6.0,1181.0,6309.0,60703,267030,Banua Wuhu,Indonesia,-5,Submarine volcano,NaN,2.0,NaN
132,578,1711,12.0,11.0,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,3000.0,3.0,3000.0
133,580,1812,8.0,6.0,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,953.0,3.0,953.0
134,581,1856,3.0,2.0,859.0,1995.0,60704,267040,Awu,Indonesia,1318,Stratovolcano,2806.0,3.0,2806.0
135,584,1892,6.0,7.0,1197.0,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,1532.0,3.0,1532.0
136,585,1913,3.0,14.0,1407.0,2973.0,60704,267040,Awu,Indonesia,1318,Stratovolcano,138.0,2.0,NaN
137,589,1966,8.0,12.0,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,39.0,4.0,39.0
138,594,1550,11.0,NaN,NaN,NaN,60801,268010,Dukono,Indonesia,1229,Complex volcano,NaN,3.0,NaN
139,599,1673,5.0,20.0,312.0,NaN,60804,268040,Gamkonora,Indonesia,1635,Stratovolcano,NaN,5.0,NaN
140,607,1608,7.0,18.0,222.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,3.0,NaN
141,617,1772,5.0,9.0,504.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,35.0,3.0,35.0
142,618,1773,2.0,2.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,2.0,NaN
143,619,1775,NaN,NaN,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,1300.0,3.0,1300.0
144,627,1838,2.0,26.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,4.0,2.0,4.0
145,629,1840,2.0,2.0,718.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,3.0,NaN
146,643,1871,8.0,7.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,1.0,2.0,1.0
147,657,1962,12.0,31.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,5.0,2.0,5.0
148,663,1550,NaN,NaN,5863.0,NaN,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,NaN,3.0,NaN
149,664,1646,7.0,19.0,5754.0,10519.0,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,NaN,4.0,NaN
150,665,1760,NaN,NaN,NaN,NaN,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,2000.0,4.0,2000.0
151,666,1861,12.0,29.0,NaN,NaN,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,326.0,4.0,326.0
152,669,1890,6.0,29.0,NaN,NaN,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,NaN,2.0,NaN
153,677,1873,1.0,16.0,NaN,NaN,70106,271060,Ragang,Philippines,2790,Stratovolcano,NaN,2.0,NaN
154,679,1871,4.0,30.0,1020.0,2179.0,70108,271080,Camiguin,Philippines,1552,Stratovolcano,NaN,2.0,NaN
155,680,1950,9.0,15.0,NaN,NaN,70108,271080,Camiguin,Philippines,1552,Stratovolcano,68.0,3.0,68.0
156,693,1996,8.0,10.0,NaN,NaN,70202,272020,Kanlaon,Philippines,2435,Stratovolcano,3.0,2.0,3.0
157,697,1933,12.0,25.0,1666.0,NaN,70301,273010,Bulusan,Philippines,1535,Stratovolcano,9.0,2.0,NaN
158,698,1978,7.0,29.0,NaN,NaN,70301,273010,Bulusan,Philippines,1535,Stratovolcano,NaN,2.0,NaN
159,704,1766,7.0,20.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,49.0,3.0,49.0
160,706,1800,10.0,30.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN
161,707,1814,2.0,1.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,1200.0,4.0,1200.0
162,712,1853,7.0,13.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,34.0,3.0,34.0
163,714,1858,1.0,NaN,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN
164,716,1871,12.0,8.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,3.0,3.0,3.0
165,724,1887,3.0,9.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,15.0,3.0,15.0
166,730,1897,5.0,23.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,350.0,3.0,350.0
167,732,1928,1.0,NaN,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,3.0,NaN
168,733,1938,6.0,5.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN
169,735,1947,1.0,7.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN
170,736,1968,4.0,21.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,6.0,3.0,6.0
171,739,1984,9.0,9.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,1.0,3.0,1.0
172,745,1572,NaN,NaN,NaN,NaN,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,3.0,NaN
173,752,1716,9.0,24.0,387.0,1205.0,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,4.0,NaN
174,753,1749,8.0,11.0,431.0,1304.0,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,3.0,NaN
175,754,1754,11.0,28.0,2853.0,1328.0,70307,273070,Taal,Philippines,311,Stratovolcano,12.0,4.0,NaN
176,756,1874,7.0,19.0,NaN,NaN,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,2.0,NaN
177,761,1911,1.0,30.0,1392.0,8391.0,70307,273070,Taal,Philippines,311,Stratovolcano,1335.0,3.0,1335.0
178,762,1965,9.0,28.0,1977.0,NaN,70307,273070,Taal,Philippines,311,Stratovolcano,355.0,4.0,355.0
179,777,1969,3.0,21.0,2872.0,NaN,70402,274020,Didicas,Philippines,228,Compound volcano,3.0,2.0,NaN
180,787,1853,10.0,29.0,809.0,NaN,80103,281030,Unnamed,Taiwan,0,Submarine volcano,NaN,2.0,NaN
181,821,1841,4.0,NaN,NaN,NaN,80205,282050,Kuchinoerabujima,Japan,657,Stratovolcano,NaN,2.0,NaN
182,823,1933,12.0,24.0,NaN,NaN,80205,282050,Kuchinoerabujima,Japan,657,Stratovolcano,8.0,4.0,8.0
183,843,764,NaN,NaN,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,80.0,4.0,80.0
184,844,766,7.0,20.0,61.0,7341.0,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,3.0,NaN
185,846,1471,11.0,3.0,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,5.0,NaN
186,858,1779,11.0,8.0,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,153.0,4.0,153.0
187,859,1781,4.0,11.0,529.0,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,38.0,4.0,23.0
188,867,1914,1.0,12.0,1412.0,2994.0,80208,282080,Aira,Japan,1117,Stratovolcano,63.0,4.0,28.0
189,874,1946,1.0,NaN,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,1.0,2.0,1.0
190,878,1955,10.0,13.0,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,3.0,NaN
191,904,1566,10.0,31.0,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,NaN,3.0,NaN
192,915,1716,11.0,9.0,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,1.0,3.0,1.0
193,916,1717,2.0,7.0,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,1.0,3.0,1.0
194,932,1792,5.0,21.0,568.0,1515.0,80210,282100,Unzendake,Japan,1483,Complex volcano,15000.0,2.0,NaN
195,933,1991,6.0,3.0,NaN,NaN,80210,282100,Unzendake,Japan,1483,Complex volcano,43.0,1.0,43.0
196,949,1331,12.0,NaN,NaN,NaN,80211,282110,Asosan,Japan,1592,Caldera,NaN,2.0,NaN
197,960,1485,1.0,NaN,NaN,NaN,80211,282110,Asosan,Japan,1592,Caldera,1.0,2.0,1.0
198,990,1826,10.0,NaN,NaN,NaN,80211,282110,Asosan,Japan,1592,Caldera,NaN,2.0,NaN
199,994,1854,2.0,NaN,NaN,NaN,80211,282110,Asosan,Japan,1592,Caldera,3.0,2.0,3.0

#### **TASK 1.2: 1 Liner Shenaniganz (7 points)**

We're going to tidy up the **new dataframe** a little more with some more advanced 1 liner code.

**Read the directions carefully and code your answer with only one line of code.**

**For this section, keep the method of display that is already in the box. Write your code as indicated.**

***YOU CAN'T USE ONE LINE LOOPS OR ANY KIND OF LOOP.***

**1.2.1:** *In one line of code, **discard any row** that contains **NaN** in **any one** of the columns indicating **time**.*

In [58]:
new_df = new_df.dropna(subset=['year', 'month', 'day'], how='any')

# KEEP THIS. It will display the whole dataframe.
new_df

,id,year,month,day,tsunamiEventId,earthquakeEventId,volcanoLocationId,volcanoLocationNewNum,name,country,elevation,morphology,deathsTotal,vei,deaths
0,1,1169,2.0,4.0,2852.0,421.0,10106,211060,Etna,Italy,3357,Stratovolcano,16000.0,NaN,NaN
3,4,1888,3.0,13.0,1175.0,NaN,50107,251070,Ritter Island,Papua New Guinea,75,Stratovolcano,NaN,2.0,NaN
5,6,1832,11.0,1.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,NaN,2.0,NaN
6,7,1977,1.0,10.0,NaN,NaN,20303,223030,Nyiragongo,"Congo, DRC",3470,Stratovolcano,NaN,1.0,NaN
8,9,1779,8.0,8.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,NaN,2.0,NaN
10,11,1907,8.0,4.0,NaN,NaN,201112,221112,Alayta,Ethiopia,1496,Shield volcano,NaN,2.0,NaN
11,12,1905,3.0,10.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,1.0,2.0,1.0
12,13,1986,7.0,24.0,NaN,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,1.0,2.0,1.0
13,14,1536,3.0,23.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,1.0,3.0,1.0
14,15,1904,2.0,25.0,NaN,NaN,30301,233010,Karthala,Comoros,2361,Shield volcano,1.0,2.0,1.0
16,17,1737,5.0,20.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,2.0,2.0,2.0
17,18,1917,4.0,1.0,NaN,NaN,40105,241050,Okataina,New Zealand,1111,Lava dome,2.0,1.0,2.0
19,20,1979,3.0,8.0,NaN,NaN,50103,251030,Karkar,Papua New Guinea,1839,Stratovolcano,2.0,2.0,2.0
20,21,1970,3.0,2.0,NaN,NaN,10101,211010,Campi Flegrei,Italy,458,Caldera,3.0,NaN,3.0
21,22,1972,6.0,9.0,NaN,NaN,30302,233020,"Fournaise, Piton de la",Reunion,2632,Shield volcano,3.0,2.0,3.0
22,23,1682,8.0,12.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,4.0,3.0,4.0
23,24,1805,8.0,11.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,4.0,2.0,4.0
24,25,1919,5.0,22.0,1476.0,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,4.0,3.0,4.0
25,26,1930,9.0,11.0,4218.0,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,6.0,3.0,5.0
26,27,1903,8.0,30.0,NaN,NaN,40105,241050,Okataina,New Zealand,1111,Lava dome,4.0,1.0,4.0
27,28,1928,11.0,2.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,5.0,1.0,5.0
28,29,1872,4.0,24.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,9.0,3.0,9.0
29,30,1979,7.0,5.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,9.0,2.0,9.0
30,31,1987,4.0,17.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,2.0,2.0,2.0
31,32,1914,9.0,10.0,NaN,NaN,40104,241040,Whakaari/White Island,New Zealand,294,Stratovolcano,11.0,NaN,11.0
32,33,1886,8.0,31.0,NaN,NaN,40311,243110,Niuafo'ou,Tonga,260,Shield volcano,NaN,4.0,NaN
33,34,1912,12.0,3.0,NaN,NaN,20302,223020,Nyamulagira,"Congo, DRC",3058,Shield volcano,20.0,3.0,20.0
34,35,1895,6.0,17.0,NaN,NaN,50103,251030,Karkar,Papua New Guinea,1839,Stratovolcano,21.0,2.0,1.0
35,36,1538,9.0,29.0,NaN,NaN,10101,211010,Campi Flegrei,Italy,458,Caldera,24.0,3.0,24.0
36,37,1853,6.0,24.0,NaN,NaN,40311,243110,Niuafo'ou,Tonga,260,Shield volcano,25.0,0.0,25.0
37,38,1954,8.0,3.0,NaN,NaN,50101,251010,Bam,Papua New Guinea,685,Stratovolcano,25.0,2.0,NaN
38,39,1944,3.0,27.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,27.0,2.0,27.0
39,40,1984,8.0,15.0,5807.0,NaN,20403,224030,Oku Volcanic Field,Cameroon,3011,Maar,37.0,NaN,37.0
41,42,1928,1.0,23.0,NaN,NaN,10204,212040,Santorini,Greece,367,Shield volcano,48.0,2.0,48.0
42,43,1631,2.0,14.0,NaN,920.0,201141,221141,Dama Ali,Ethiopia,1068,Shield volcano,50.0,NaN,50.0
43,44,1843,11.0,17.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,56.0,2.0,56.0
44,45,1944,12.0,4.0,NaN,NaN,60320,263200,Dieng Volcanic Complex,Indonesia,2565,Complex volcano,117.0,2.0,117.0
45,49,1979,2.0,20.0,NaN,NaN,60320,263200,Dieng Volcanic Complex,Indonesia,2565,Complex volcano,149.0,1.0,149.0
47,64,1672,8.0,4.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,3000.0,3.0,3000.0
48,69,1822,12.0,27.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,100.0,3.0,100.0
49,71,1832,12.0,25.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,32.0,3.0,32.0
50,81,1872,4.0,15.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,30.0,4.0,30.0
51,82,1872,11.0,3.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,200.0,4.0,200.0
53,92,1920,7.0,25.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,33.0,3.0,33.0
54,94,1930,12.0,18.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,1369.0,3.0,1369.0
55,100,1953,3.0,23.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,64.0,3.0,64.0
56,104,1961,5.0,8.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,6.0,3.0,6.0
57,105,1969,1.0,7.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,3.0,2.0,3.0
58,111,1986,10.0,15.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,1.0,2.0,1.0
59,112,1994,11.0,22.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,60.0,3.0,60.0
65,128,1716,7.0,20.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,2.0,NaN
66,132,1826,10.0,11.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN
67,133,1848,5.0,16.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,21.0,2.0,21.0
68,135,1864,1.0,3.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,54.0,2.0,54.0
69,136,1875,1.0,29.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,0.0,NaN
70,137,1901,5.0,22.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN
71,138,1919,5.0,19.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,5110.0,4.0,5110.0
72,140,1951,8.0,31.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,7.0,3.0,7.0
73,141,1966,4.0,26.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,215.0,4.0,215.0
74,144,1990,2.0,10.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,32.0,4.0,32.0
76,167,1885,4.0,18.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,74.0,2.0,74.0
77,176,1895,5.0,22.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN
79,193,1911,11.0,8.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,3.0,NaN
80,195,1913,6.0,23.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN
81,196,1941,9.0,21.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN
83,199,1946,10.0,29.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN
84,200,1950,8.0,28.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,6.0,1.0,6.0
85,201,1963,5.0,5.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,1.0,2.0,1.0
86,202,1967,8.0,31.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,3.0,3.0,3.0
87,203,1985,5.0,10.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,70.0,3.0,70.0
88,204,1978,9.0,19.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,12.0,3.0,12.0
89,205,1976,8.0,31.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,119.0,2.0,119.0
90,206,1981,3.0,29.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,1.0,3.0,1.0
98,333,1817,1.0,24.0,NaN,NaN,60335,263350,Ijen,Indonesia,2769,Stratovolcano,NaN,2.0,NaN
99,345,1963,9.0,5.0,NaN,NaN,60401,264010,Batur,Indonesia,1717,Caldera,2.0,2.0,2.0
100,351,1963,3.0,18.0,1942.0,NaN,60402,264020,Agung,Indonesia,2997,Stratovolcano,1028.0,5.0,1028.0
101,353,1963,5.0,16.0,NaN,4292.0,60402,264020,Agung,Indonesia,2997,Stratovolcano,120.0,3.0,120.0
102,367,1815,4.0,10.0,613.0,NaN,60404,264040,Tambora,Indonesia,2850,Stratovolcano,60000.0,7.0,11000.0
103,389,1969,1.0,28.0,NaN,NaN,60411,264110,Iya,Indonesia,618,Stratovolcano,2.0,3.0,2.0
104,394,1928,8.0,4.0,1607.0,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,226.0,3.0,98.0
105,395,1964,1.0,1.0,NaN,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,1.0,2.0,1.0
107,398,1981,9.0,5.0,NaN,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,NaN,2.0,NaN
108,410,1869,7.0,7.0,NaN,NaN,60418,264180,Lewotobi,Indonesia,1703,Stratovolcano,2.0,2.0,2.0
109,411,1907,9.0,28.0,NaN,NaN,60418,264180,Lewotobi,Indonesia,1703,Stratovolcano,1.0,2.0,1.0
111,441,1948,4.0,7.0,NaN,NaN,60425,264250,Iliwerung,Indonesia,583,Complex volcano,NaN,2.0,NaN
113,447,1983,8.0,17.0,4702.0,NaN,60425,264250,Iliwerung,Indonesia,583,Complex volcano,NaN,1.0,NaN
115,457,1659,11.0,11.0,285.0,NaN,60505,265050,Teon,Pacific Ocean,728,Stratovolcano,NaN,4.0,NaN
117,466,1692,6.0,4.0,NaN,NaN,60507,265070,Serua,Pacific Ocean,608,Stratovolcano,NaN,4.0,NaN
120,477,1694,11.0,20.0,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,NaN,3.0,NaN
121,482,1820,6.0,11.0,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,NaN,2.0,NaN
122,486,1988,5.0,9.0,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,4.0,3.0,4.0
123,488,1983,7.0,23.0,NaN,NaN,60601,266010,Colo,Indonesia,404,Stratovolcano,NaN,4.0,NaN
124,489,1845,2.0,8.0,741.0,1865.0,60603,266030,Soputan,Indonesia,1785,Stratovolcano,118.0,2.0,NaN
125,525,1958,7.0,12.0,NaN,NaN,60611,266110,Mahawu,Indonesia,1299,Stratovolcano,1.0,2.0,1.0
127,533,1871,3.0,3.0,1022.0,NaN,60701,267010,Ruang,Indonesia,725,Stratovolcano,400.0,2.0,NaN
128,552,1940,6.0,20.0,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,1.0,2.0,1.0
129,561,1974,2.0,11.0,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,4.0,3.0,4.0
130,562,1976,9.0,15.0,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,1.0,2.0,1.0
131,569,1889,9.0,6.0,1181.0,6309.0,60703,267030,Banua Wuhu,Indonesia,-5,Submarine volcano,NaN,2.0,NaN
132,578,1711,12.0,11.0,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,3000.0,3.0,3000.0
133,580,1812,8.0,6.0,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,953.0,3.0,953.0
134,581,1856,3.0,2.0,859.0,1995.0,60704,267040,Awu,Indonesia,1318,Stratovolcano,2806.0,3.0,2806.0
135,584,1892,6.0,7.0,1197.0,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,1532.0,3.0,1532.0
136,585,1913,3.0,14.0,1407.0,2973.0,60704,267040,Awu,Indonesia,1318,Stratovolcano,138.0,2.0,NaN
137,589,1966,8.0,12.0,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,39.0,4.0,39.0
139,599,1673,5.0,20.0,312.0,NaN,60804,268040,Gamkonora,Indonesia,1635,Stratovolcano,NaN,5.0,NaN
140,607,1608,7.0,18.0,222.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,3.0,NaN
141,617,1772,5.0,9.0,504.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,35.0,3.0,35.0
142,618,1773,2.0,2.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,2.0,NaN
144,627,1838,2.0,26.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,4.0,2.0,4.0
145,629,1840,2.0,2.0,718.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,3.0,NaN
146,643,1871,8.0,7.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,1.0,2.0,1.0
147,657,1962,12.0,31.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,5.0,2.0,5.0
149,664,1646,7.0,19.0,5754.0,10519.0,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,NaN,4.0,NaN
151,666,1861,12.0,29.0,NaN,NaN,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,326.0,4.0,326.0
152,669,1890,6.0,29.0,NaN,NaN,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,NaN,2.0,NaN
153,677,1873,1.0,16.0,NaN,NaN,70106,271060,Ragang,Philippines,2790,Stratovolcano,NaN,2.0,NaN
154,679,1871,4.0,30.0,1020.0,2179.0,70108,271080,Camiguin,Philippines,1552,Stratovolcano,NaN,2.0,NaN
155,680,1950,9.0,15.0,NaN,NaN,70108,271080,Camiguin,Philippines,1552,Stratovolcano,68.0,3.0,68.0
156,693,1996,8.0,10.0,NaN,NaN,70202,272020,Kanlaon,Philippines,2435,Stratovolcano,3.0,2.0,3.0
157,697,1933,12.0,25.0,1666.0,NaN,70301,273010,Bulusan,Philippines,1535,Stratovolcano,9.0,2.0,NaN
158,698,1978,7.0,29.0,NaN,NaN,70301,273010,Bulusan,Philippines,1535,Stratovolcano,NaN,2.0,NaN
159,704,1766,7.0,20.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,49.0,3.0,49.0
160,706,1800,10.0,30.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN
161,707,1814,2.0,1.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,1200.0,4.0,1200.0
162,712,1853,7.0,13.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,34.0,3.0,34.0
164,716,1871,12.0,8.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,3.0,3.0,3.0
165,724,1887,3.0,9.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,15.0,3.0,15.0
166,730,1897,5.0,23.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,350.0,3.0,350.0
168,733,1938,6.0,5.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN
169,735,1947,1.0,7.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN
170,736,1968,4.0,21.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,6.0,3.0,6.0
171,739,1984,9.0,9.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,1.0,3.0,1.0
173,752,1716,9.0,24.0,387.0,1205.0,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,4.0,NaN
174,753,1749,8.0,11.0,431.0,1304.0,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,3.0,NaN
175,754,1754,11.0,28.0,2853.0,1328.0,70307,273070,Taal,Philippines,311,Stratovolcano,12.0,4.0,NaN
176,756,1874,7.0,19.0,NaN,NaN,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,2.0,NaN
177,761,1911,1.0,30.0,1392.0,8391.0,70307,273070,Taal,Philippines,311,Stratovolcano,1335.0,3.0,1335.0
178,762,1965,9.0,28.0,1977.0,NaN,70307,273070,Taal,Philippines,311,Stratovolcano,355.0,4.0,355.0
179,777,1969,3.0,21.0,2872.0,NaN,70402,274020,Didicas,Philippines,228,Compound volcano,3.0,2.0,NaN
180,787,1853,10.0,29.0,809.0,NaN,80103,281030,Unnamed,Taiwan,0,Submarine volcano,NaN,2.0,NaN
182,823,1933,12.0,24.0,NaN,NaN,80205,282050,Kuchinoerabujima,Japan,657,Stratovolcano,8.0,4.0,8.0
184,844,766,7.0,20.0,61.0,7341.0,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,3.0,NaN
185,846,1471,11.0,3.0,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,5.0,NaN
186,858,1779,11.0,8.0,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,153.0,4.0,153.0
187,859,1781,4.0,11.0,529.0,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,38.0,4.0,23.0
188,867,1914,1.0,12.0,1412.0,2994.0,80208,282080,Aira,Japan,1117,Stratovolcano,63.0,4.0,28.0
190,878,1955,10.0,13.0,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,3.0,NaN
191,904,1566,10.0,31.0,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,NaN,3.0,NaN
192,915,1716,11.0,9.0,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,1.0,3.0,1.0
193,916,1717,2.0,7.0,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,1.0,3.0,1.0
194,932,1792,5.0,21.0,568.0,1515.0,80210,282100,Unzendake,Japan,1483,Complex volcano,15000.0,2.0,NaN
195,933,1991,6.0,3.0,NaN,NaN,80210,282100,Unzendake,Japan,1483,Complex volcano,43.0,1.0,43.0

**1.2.2:** *In one line of code, **reset** the **index column** of the dataframe so that it has **1-based indexing**.*

In [59]:
new_df = new_df.reset_index(drop=True).set_index(new_df.index + 1)

# KEEP THIS. It will display the whole dataframe.
new_df

,id,year,month,day,tsunamiEventId,earthquakeEventId,volcanoLocationId,volcanoLocationNewNum,name,country,elevation,morphology,deathsTotal,vei,deaths
1,1,1169,2.0,4.0,2852.0,421.0,10106,211060,Etna,Italy,3357,Stratovolcano,16000.0,NaN,NaN
4,4,1888,3.0,13.0,1175.0,NaN,50107,251070,Ritter Island,Papua New Guinea,75,Stratovolcano,NaN,2.0,NaN
6,6,1832,11.0,1.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,NaN,2.0,NaN
7,7,1977,1.0,10.0,NaN,NaN,20303,223030,Nyiragongo,"Congo, DRC",3470,Stratovolcano,NaN,1.0,NaN
9,9,1779,8.0,8.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,NaN,2.0,NaN
11,11,1907,8.0,4.0,NaN,NaN,201112,221112,Alayta,Ethiopia,1496,Shield volcano,NaN,2.0,NaN
12,12,1905,3.0,10.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,1.0,2.0,1.0
13,13,1986,7.0,24.0,NaN,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,1.0,2.0,1.0
14,14,1536,3.0,23.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,1.0,3.0,1.0
15,15,1904,2.0,25.0,NaN,NaN,30301,233010,Karthala,Comoros,2361,Shield volcano,1.0,2.0,1.0
17,17,1737,5.0,20.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,2.0,2.0,2.0
18,18,1917,4.0,1.0,NaN,NaN,40105,241050,Okataina,New Zealand,1111,Lava dome,2.0,1.0,2.0
20,20,1979,3.0,8.0,NaN,NaN,50103,251030,Karkar,Papua New Guinea,1839,Stratovolcano,2.0,2.0,2.0
21,21,1970,3.0,2.0,NaN,NaN,10101,211010,Campi Flegrei,Italy,458,Caldera,3.0,NaN,3.0
22,22,1972,6.0,9.0,NaN,NaN,30302,233020,"Fournaise, Piton de la",Reunion,2632,Shield volcano,3.0,2.0,3.0
23,23,1682,8.0,12.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,4.0,3.0,4.0
24,24,1805,8.0,11.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,4.0,2.0,4.0
25,25,1919,5.0,22.0,1476.0,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,4.0,3.0,4.0
26,26,1930,9.0,11.0,4218.0,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,6.0,3.0,5.0
27,27,1903,8.0,30.0,NaN,NaN,40105,241050,Okataina,New Zealand,1111,Lava dome,4.0,1.0,4.0
28,28,1928,11.0,2.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,5.0,1.0,5.0
29,29,1872,4.0,24.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,9.0,3.0,9.0
30,30,1979,7.0,5.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,9.0,2.0,9.0
31,31,1987,4.0,17.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,2.0,2.0,2.0
32,32,1914,9.0,10.0,NaN,NaN,40104,241040,Whakaari/White Island,New Zealand,294,Stratovolcano,11.0,NaN,11.0
33,33,1886,8.0,31.0,NaN,NaN,40311,243110,Niuafo'ou,Tonga,260,Shield volcano,NaN,4.0,NaN
34,34,1912,12.0,3.0,NaN,NaN,20302,223020,Nyamulagira,"Congo, DRC",3058,Shield volcano,20.0,3.0,20.0
35,35,1895,6.0,17.0,NaN,NaN,50103,251030,Karkar,Papua New Guinea,1839,Stratovolcano,21.0,2.0,1.0
36,36,1538,9.0,29.0,NaN,NaN,10101,211010,Campi Flegrei,Italy,458,Caldera,24.0,3.0,24.0
37,37,1853,6.0,24.0,NaN,NaN,40311,243110,Niuafo'ou,Tonga,260,Shield volcano,25.0,0.0,25.0
38,38,1954,8.0,3.0,NaN,NaN,50101,251010,Bam,Papua New Guinea,685,Stratovolcano,25.0,2.0,NaN
39,39,1944,3.0,27.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,27.0,2.0,27.0
40,40,1984,8.0,15.0,5807.0,NaN,20403,224030,Oku Volcanic Field,Cameroon,3011,Maar,37.0,NaN,37.0
42,42,1928,1.0,23.0,NaN,NaN,10204,212040,Santorini,Greece,367,Shield volcano,48.0,2.0,48.0
43,43,1631,2.0,14.0,NaN,920.0,201141,221141,Dama Ali,Ethiopia,1068,Shield volcano,50.0,NaN,50.0
44,44,1843,11.0,17.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,56.0,2.0,56.0
45,45,1944,12.0,4.0,NaN,NaN,60320,263200,Dieng Volcanic Complex,Indonesia,2565,Complex volcano,117.0,2.0,117.0
46,49,1979,2.0,20.0,NaN,NaN,60320,263200,Dieng Volcanic Complex,Indonesia,2565,Complex volcano,149.0,1.0,149.0
48,64,1672,8.0,4.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,3000.0,3.0,3000.0
49,69,1822,12.0,27.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,100.0,3.0,100.0
50,71,1832,12.0,25.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,32.0,3.0,32.0
51,81,1872,4.0,15.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,30.0,4.0,30.0
52,82,1872,11.0,3.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,200.0,4.0,200.0
54,92,1920,7.0,25.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,33.0,3.0,33.0
55,94,1930,12.0,18.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,1369.0,3.0,1369.0
56,100,1953,3.0,23.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,64.0,3.0,64.0
57,104,1961,5.0,8.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,6.0,3.0,6.0
58,105,1969,1.0,7.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,3.0,2.0,3.0
59,111,1986,10.0,15.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,1.0,2.0,1.0
60,112,1994,11.0,22.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,60.0,3.0,60.0
66,128,1716,7.0,20.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,2.0,NaN
67,132,1826,10.0,11.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN
68,133,1848,5.0,16.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,21.0,2.0,21.0
69,135,1864,1.0,3.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,54.0,2.0,54.0
70,136,1875,1.0,29.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,0.0,NaN
71,137,1901,5.0,22.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN
72,138,1919,5.0,19.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,5110.0,4.0,5110.0
73,140,1951,8.0,31.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,7.0,3.0,7.0
74,141,1966,4.0,26.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,215.0,4.0,215.0
75,144,1990,2.0,10.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,32.0,4.0,32.0
77,167,1885,4.0,18.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,74.0,2.0,74.0
78,176,1895,5.0,22.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN
80,193,1911,11.0,8.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,3.0,NaN
81,195,1913,6.0,23.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN
82,196,1941,9.0,21.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN
84,199,1946,10.0,29.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN
85,200,1950,8.0,28.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,6.0,1.0,6.0
86,201,1963,5.0,5.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,1.0,2.0,1.0
87,202,1967,8.0,31.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,3.0,3.0,3.0
88,203,1985,5.0,10.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,70.0,3.0,70.0
89,204,1978,9.0,19.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,12.0,3.0,12.0
90,205,1976,8.0,31.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,119.0,2.0,119.0
91,206,1981,3.0,29.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,1.0,3.0,1.0
99,333,1817,1.0,24.0,NaN,NaN,60335,263350,Ijen,Indonesia,2769,Stratovolcano,NaN,2.0,NaN
100,345,1963,9.0,5.0,NaN,NaN,60401,264010,Batur,Indonesia,1717,Caldera,2.0,2.0,2.0
101,351,1963,3.0,18.0,1942.0,NaN,60402,264020,Agung,Indonesia,2997,Stratovolcano,1028.0,5.0,1028.0
102,353,1963,5.0,16.0,NaN,4292.0,60402,264020,Agung,Indonesia,2997,Stratovolcano,120.0,3.0,120.0
103,367,1815,4.0,10.0,613.0,NaN,60404,264040,Tambora,Indonesia,2850,Stratovolcano,60000.0,7.0,11000.0
104,389,1969,1.0,28.0,NaN,NaN,60411,264110,Iya,Indonesia,618,Stratovolcano,2.0,3.0,2.0
105,394,1928,8.0,4.0,1607.0,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,226.0,3.0,98.0
106,395,1964,1.0,1.0,NaN,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,1.0,2.0,1.0
108,398,1981,9.0,5.0,NaN,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,NaN,2.0,NaN
109,410,1869,7.0,7.0,NaN,NaN,60418,264180,Lewotobi,Indonesia,1703,Stratovolcano,2.0,2.0,2.0
110,411,1907,9.0,28.0,NaN,NaN,60418,264180,Lewotobi,Indonesia,1703,Stratovolcano,1.0,2.0,1.0
112,441,1948,4.0,7.0,NaN,NaN,60425,264250,Iliwerung,Indonesia,583,Complex volcano,NaN,2.0,NaN
114,447,1983,8.0,17.0,4702.0,NaN,60425,264250,Iliwerung,Indonesia,583,Complex volcano,NaN,1.0,NaN
116,457,1659,11.0,11.0,285.0,NaN,60505,265050,Teon,Pacific Ocean,728,Stratovolcano,NaN,4.0,NaN
118,466,1692,6.0,4.0,NaN,NaN,60507,265070,Serua,Pacific Ocean,608,Stratovolcano,NaN,4.0,NaN
121,477,1694,11.0,20.0,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,NaN,3.0,NaN
122,482,1820,6.0,11.0,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,NaN,2.0,NaN
123,486,1988,5.0,9.0,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,4.0,3.0,4.0
124,488,1983,7.0,23.0,NaN,NaN,60601,266010,Colo,Indonesia,404,Stratovolcano,NaN,4.0,NaN
125,489,1845,2.0,8.0,741.0,1865.0,60603,266030,Soputan,Indonesia,1785,Stratovolcano,118.0,2.0,NaN
126,525,1958,7.0,12.0,NaN,NaN,60611,266110,Mahawu,Indonesia,1299,Stratovolcano,1.0,2.0,1.0
128,533,1871,3.0,3.0,1022.0,NaN,60701,267010,Ruang,Indonesia,725,Stratovolcano,400.0,2.0,NaN
129,552,1940,6.0,20.0,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,1.0,2.0,1.0
130,561,1974,2.0,11.0,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,4.0,3.0,4.0
131,562,1976,9.0,15.0,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,1.0,2.0,1.0
132,569,1889,9.0,6.0,1181.0,6309.0,60703,267030,Banua Wuhu,Indonesia,-5,Submarine volcano,NaN,2.0,NaN
133,578,1711,12.0,11.0,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,3000.0,3.0,3000.0
134,580,1812,8.0,6.0,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,953.0,3.0,953.0
135,581,1856,3.0,2.0,859.0,1995.0,60704,267040,Awu,Indonesia,1318,Stratovolcano,2806.0,3.0,2806.0
136,584,1892,6.0,7.0,1197.0,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,1532.0,3.0,1532.0
137,585,1913,3.0,14.0,1407.0,2973.0,60704,267040,Awu,Indonesia,1318,Stratovolcano,138.0,2.0,NaN
138,589,1966,8.0,12.0,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,39.0,4.0,39.0
140,599,1673,5.0,20.0,312.0,NaN,60804,268040,Gamkonora,Indonesia,1635,Stratovolcano,NaN,5.0,NaN
141,607,1608,7.0,18.0,222.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,3.0,NaN
142,617,1772,5.0,9.0,504.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,35.0,3.0,35.0
143,618,1773,2.0,2.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,2.0,NaN
145,627,1838,2.0,26.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,4.0,2.0,4.0
146,629,1840,2.0,2.0,718.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,3.0,NaN
147,643,1871,8.0,7.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,1.0,2.0,1.0
148,657,1962,12.0,31.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,5.0,2.0,5.0
150,664,1646,7.0,19.0,5754.0,10519.0,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,NaN,4.0,NaN
152,666,1861,12.0,29.0,NaN,NaN,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,326.0,4.0,326.0
153,669,1890,6.0,29.0,NaN,NaN,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,NaN,2.0,NaN
154,677,1873,1.0,16.0,NaN,NaN,70106,271060,Ragang,Philippines,2790,Stratovolcano,NaN,2.0,NaN
155,679,1871,4.0,30.0,1020.0,2179.0,70108,271080,Camiguin,Philippines,1552,Stratovolcano,NaN,2.0,NaN
156,680,1950,9.0,15.0,NaN,NaN,70108,271080,Camiguin,Philippines,1552,Stratovolcano,68.0,3.0,68.0
157,693,1996,8.0,10.0,NaN,NaN,70202,272020,Kanlaon,Philippines,2435,Stratovolcano,3.0,2.0,3.0
158,697,1933,12.0,25.0,1666.0,NaN,70301,273010,Bulusan,Philippines,1535,Stratovolcano,9.0,2.0,NaN
159,698,1978,7.0,29.0,NaN,NaN,70301,273010,Bulusan,Philippines,1535,Stratovolcano,NaN,2.0,NaN
160,704,1766,7.0,20.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,49.0,3.0,49.0
161,706,1800,10.0,30.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN
162,707,1814,2.0,1.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,1200.0,4.0,1200.0
163,712,1853,7.0,13.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,34.0,3.0,34.0
165,716,1871,12.0,8.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,3.0,3.0,3.0
166,724,1887,3.0,9.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,15.0,3.0,15.0
167,730,1897,5.0,23.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,350.0,3.0,350.0
169,733,1938,6.0,5.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN
170,735,1947,1.0,7.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN
171,736,1968,4.0,21.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,6.0,3.0,6.0
172,739,1984,9.0,9.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,1.0,3.0,1.0
174,752,1716,9.0,24.0,387.0,1205.0,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,4.0,NaN
175,753,1749,8.0,11.0,431.0,1304.0,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,3.0,NaN
176,754,1754,11.0,28.0,2853.0,1328.0,70307,273070,Taal,Philippines,311,Stratovolcano,12.0,4.0,NaN
177,756,1874,7.0,19.0,NaN,NaN,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,2.0,NaN
178,761,1911,1.0,30.0,1392.0,8391.0,70307,273070,Taal,Philippines,311,Stratovolcano,1335.0,3.0,1335.0
179,762,1965,9.0,28.0,1977.0,NaN,70307,273070,Taal,Philippines,311,Stratovolcano,355.0,4.0,355.0
180,777,1969,3.0,21.0,2872.0,NaN,70402,274020,Didicas,Philippines,228,Compound volcano,3.0,2.0,NaN
181,787,1853,10.0,29.0,809.0,NaN,80103,281030,Unnamed,Taiwan,0,Submarine volcano,NaN,2.0,NaN
183,823,1933,12.0,24.0,NaN,NaN,80205,282050,Kuchinoerabujima,Japan,657,Stratovolcano,8.0,4.0,8.0
185,844,766,7.0,20.0,61.0,7341.0,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,3.0,NaN
186,846,1471,11.0,3.0,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,5.0,NaN
187,858,1779,11.0,8.0,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,153.0,4.0,153.0
188,859,1781,4.0,11.0,529.0,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,38.0,4.0,23.0
189,867,1914,1.0,12.0,1412.0,2994.0,80208,282080,Aira,Japan,1117,Stratovolcano,63.0,4.0,28.0
191,878,1955,10.0,13.0,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,3.0,NaN
192,904,1566,10.0,31.0,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,NaN,3.0,NaN
193,915,1716,11.0,9.0,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,1.0,3.0,1.0
194,916,1717,2.0,7.0,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,1.0,3.0,1.0
195,932,1792,5.0,21.0,568.0,1515.0,80210,282100,Unzendake,Japan,1483,Complex volcano,15000.0,2.0,NaN
196,933,1991,6.0,3.0,NaN,NaN,80210,282100,Unzendake,Japan,1483,Complex volcano,43.0,1.0,43.0

The **deathsTotal** and **deaths**  columns have approximations of the same data with alternating NaNs in each.

**1.2.3:** *In one line of code, make a **new column** called **'totalDeaths'** that takes the **max** of the values given between those* ***two*** *columns. If there is* ***NaN*** *in* ***one column*** *and a* ***numerical*** *value in the* ***other***, *it will ***take the numerical value***. ***Only*** if there are* ***NaNs*** *in* ***both*** *columns, the* ***new column will have NaN.***

In [60]:
new_df['totalDeaths'] = new_df[['deathsTotal', 'deaths']].max(axis=1)

# KEEP THIS. It will display the whole dataframe.
new_df

,id,year,month,day,tsunamiEventId,earthquakeEventId,volcanoLocationId,volcanoLocationNewNum,name,country,elevation,morphology,deathsTotal,vei,deaths,totalDeaths
1,1,1169,2.0,4.0,2852.0,421.0,10106,211060,Etna,Italy,3357,Stratovolcano,16000.0,NaN,NaN,16000.0
4,4,1888,3.0,13.0,1175.0,NaN,50107,251070,Ritter Island,Papua New Guinea,75,Stratovolcano,NaN,2.0,NaN,NaN
6,6,1832,11.0,1.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,NaN,2.0,NaN,NaN
7,7,1977,1.0,10.0,NaN,NaN,20303,223030,Nyiragongo,"Congo, DRC",3470,Stratovolcano,NaN,1.0,NaN,NaN
9,9,1779,8.0,8.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,NaN,2.0,NaN,NaN
11,11,1907,8.0,4.0,NaN,NaN,201112,221112,Alayta,Ethiopia,1496,Shield volcano,NaN,2.0,NaN,NaN
12,12,1905,3.0,10.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,1.0,2.0,1.0,1.0
13,13,1986,7.0,24.0,NaN,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,1.0,2.0,1.0,1.0
14,14,1536,3.0,23.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,1.0,3.0,1.0,1.0
15,15,1904,2.0,25.0,NaN,NaN,30301,233010,Karthala,Comoros,2361,Shield volcano,1.0,2.0,1.0,1.0
17,17,1737,5.0,20.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,2.0,2.0,2.0,2.0
18,18,1917,4.0,1.0,NaN,NaN,40105,241050,Okataina,New Zealand,1111,Lava dome,2.0,1.0,2.0,2.0
20,20,1979,3.0,8.0,NaN,NaN,50103,251030,Karkar,Papua New Guinea,1839,Stratovolcano,2.0,2.0,2.0,2.0
21,21,1970,3.0,2.0,NaN,NaN,10101,211010,Campi Flegrei,Italy,458,Caldera,3.0,NaN,3.0,3.0
22,22,1972,6.0,9.0,NaN,NaN,30302,233020,"Fournaise, Piton de la",Reunion,2632,Shield volcano,3.0,2.0,3.0,3.0
23,23,1682,8.0,12.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,4.0,3.0,4.0,4.0
24,24,1805,8.0,11.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,4.0,2.0,4.0,4.0
25,25,1919,5.0,22.0,1476.0,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,4.0,3.0,4.0,4.0
26,26,1930,9.0,11.0,4218.0,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,6.0,3.0,5.0,6.0
27,27,1903,8.0,30.0,NaN,NaN,40105,241050,Okataina,New Zealand,1111,Lava dome,4.0,1.0,4.0,4.0
28,28,1928,11.0,2.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,5.0,1.0,5.0,5.0
29,29,1872,4.0,24.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,9.0,3.0,9.0,9.0
30,30,1979,7.0,5.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,9.0,2.0,9.0,9.0
31,31,1987,4.0,17.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,2.0,2.0,2.0,2.0
32,32,1914,9.0,10.0,NaN,NaN,40104,241040,Whakaari/White Island,New Zealand,294,Stratovolcano,11.0,NaN,11.0,11.0
33,33,1886,8.0,31.0,NaN,NaN,40311,243110,Niuafo'ou,Tonga,260,Shield volcano,NaN,4.0,NaN,NaN
34,34,1912,12.0,3.0,NaN,NaN,20302,223020,Nyamulagira,"Congo, DRC",3058,Shield volcano,20.0,3.0,20.0,20.0
35,35,1895,6.0,17.0,NaN,NaN,50103,251030,Karkar,Papua New Guinea,1839,Stratovolcano,21.0,2.0,1.0,21.0
36,36,1538,9.0,29.0,NaN,NaN,10101,211010,Campi Flegrei,Italy,458,Caldera,24.0,3.0,24.0,24.0
37,37,1853,6.0,24.0,NaN,NaN,40311,243110,Niuafo'ou,Tonga,260,Shield volcano,25.0,0.0,25.0,25.0
38,38,1954,8.0,3.0,NaN,NaN,50101,251010,Bam,Papua New Guinea,685,Stratovolcano,25.0,2.0,NaN,25.0
39,39,1944,3.0,27.0,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,27.0,2.0,27.0,27.0
40,40,1984,8.0,15.0,5807.0,NaN,20403,224030,Oku Volcanic Field,Cameroon,3011,Maar,37.0,NaN,37.0,37.0
42,42,1928,1.0,23.0,NaN,NaN,10204,212040,Santorini,Greece,367,Shield volcano,48.0,2.0,48.0,48.0
43,43,1631,2.0,14.0,NaN,920.0,201141,221141,Dama Ali,Ethiopia,1068,Shield volcano,50.0,NaN,50.0,50.0
44,44,1843,11.0,17.0,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,56.0,2.0,56.0,56.0
45,45,1944,12.0,4.0,NaN,NaN,60320,263200,Dieng Volcanic Complex,Indonesia,2565,Complex volcano,117.0,2.0,117.0,117.0
46,49,1979,2.0,20.0,NaN,NaN,60320,263200,Dieng Volcanic Complex,Indonesia,2565,Complex volcano,149.0,1.0,149.0,149.0
48,64,1672,8.0,4.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,3000.0,3.0,3000.0,3000.0
49,69,1822,12.0,27.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,100.0,3.0,100.0,100.0
50,71,1832,12.0,25.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,32.0,3.0,32.0,32.0
51,81,1872,4.0,15.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,30.0,4.0,30.0,30.0
52,82,1872,11.0,3.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,200.0,4.0,200.0,200.0
54,92,1920,7.0,25.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,33.0,3.0,33.0,33.0
55,94,1930,12.0,18.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,1369.0,3.0,1369.0,1369.0
56,100,1953,3.0,23.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,64.0,3.0,64.0,64.0
57,104,1961,5.0,8.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,6.0,3.0,6.0,6.0
58,105,1969,1.0,7.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,3.0,2.0,3.0,3.0
59,111,1986,10.0,15.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,1.0,2.0,1.0,1.0
60,112,1994,11.0,22.0,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,60.0,3.0,60.0,60.0
66,128,1716,7.0,20.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,2.0,NaN,NaN
67,132,1826,10.0,11.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN,NaN
68,133,1848,5.0,16.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,21.0,2.0,21.0,21.0
69,135,1864,1.0,3.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,54.0,2.0,54.0,54.0
70,136,1875,1.0,29.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,0.0,NaN,NaN
71,137,1901,5.0,22.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN,NaN
72,138,1919,5.0,19.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,5110.0,4.0,5110.0,5110.0
73,140,1951,8.0,31.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,7.0,3.0,7.0,7.0
74,141,1966,4.0,26.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,215.0,4.0,215.0,215.0
75,144,1990,2.0,10.0,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,32.0,4.0,32.0,32.0
77,167,1885,4.0,18.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,74.0,2.0,74.0,74.0
78,176,1895,5.0,22.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN,NaN
80,193,1911,11.0,8.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,3.0,NaN,NaN
81,195,1913,6.0,23.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN,NaN
82,196,1941,9.0,21.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN,NaN
84,199,1946,10.0,29.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN,NaN
85,200,1950,8.0,28.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,6.0,1.0,6.0,6.0
86,201,1963,5.0,5.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,1.0,2.0,1.0,1.0
87,202,1967,8.0,31.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,3.0,3.0,3.0,3.0
88,203,1985,5.0,10.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,70.0,3.0,70.0,70.0
89,204,1978,9.0,19.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,12.0,3.0,12.0,12.0
90,205,1976,8.0,31.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,119.0,2.0,119.0,119.0
91,206,1981,3.0,29.0,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,1.0,3.0,1.0,1.0
99,333,1817,1.0,24.0,NaN,NaN,60335,263350,Ijen,Indonesia,2769,Stratovolcano,NaN,2.0,NaN,NaN
100,345,1963,9.0,5.0,NaN,NaN,60401,264010,Batur,Indonesia,1717,Caldera,2.0,2.0,2.0,2.0
101,351,1963,3.0,18.0,1942.0,NaN,60402,264020,Agung,Indonesia,2997,Stratovolcano,1028.0,5.0,1028.0,1028.0
102,353,1963,5.0,16.0,NaN,4292.0,60402,264020,Agung,Indonesia,2997,Stratovolcano,120.0,3.0,120.0,120.0
103,367,1815,4.0,10.0,613.0,NaN,60404,264040,Tambora,Indonesia,2850,Stratovolcano,60000.0,7.0,11000.0,60000.0
104,389,1969,1.0,28.0,NaN,NaN,60411,264110,Iya,Indonesia,618,Stratovolcano,2.0,3.0,2.0,2.0
105,394,1928,8.0,4.0,1607.0,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,226.0,3.0,98.0,226.0
106,395,1964,1.0,1.0,NaN,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,1.0,2.0,1.0,1.0
108,398,1981,9.0,5.0,NaN,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,NaN,2.0,NaN,NaN
109,410,1869,7.0,7.0,NaN,NaN,60418,264180,Lewotobi,Indonesia,1703,Stratovolcano,2.0,2.0,2.0,2.0
110,411,1907,9.0,28.0,NaN,NaN,60418,264180,Lewotobi,Indonesia,1703,Stratovolcano,1.0,2.0,1.0,1.0
112,441,1948,4.0,7.0,NaN,NaN,60425,264250,Iliwerung,Indonesia,583,Complex volcano,NaN,2.0,NaN,NaN
114,447,1983,8.0,17.0,4702.0,NaN,60425,264250,Iliwerung,Indonesia,583,Complex volcano,NaN,1.0,NaN,NaN
116,457,1659,11.0,11.0,285.0,NaN,60505,265050,Teon,Pacific Ocean,728,Stratovolcano,NaN,4.0,NaN,NaN
118,466,1692,6.0,4.0,NaN,NaN,60507,265070,Serua,Pacific Ocean,608,Stratovolcano,NaN,4.0,NaN,NaN
121,477,1694,11.0,20.0,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,NaN,3.0,NaN,NaN
122,482,1820,6.0,11.0,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,NaN,2.0,NaN,NaN
123,486,1988,5.0,9.0,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,4.0,3.0,4.0,4.0
124,488,1983,7.0,23.0,NaN,NaN,60601,266010,Colo,Indonesia,404,Stratovolcano,NaN,4.0,NaN,NaN
125,489,1845,2.0,8.0,741.0,1865.0,60603,266030,Soputan,Indonesia,1785,Stratovolcano,118.0,2.0,NaN,118.0
126,525,1958,7.0,12.0,NaN,NaN,60611,266110,Mahawu,Indonesia,1299,Stratovolcano,1.0,2.0,1.0,1.0
128,533,1871,3.0,3.0,1022.0,NaN,60701,267010,Ruang,Indonesia,725,Stratovolcano,400.0,2.0,NaN,400.0
129,552,1940,6.0,20.0,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,1.0,2.0,1.0,1.0
130,561,1974,2.0,11.0,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,4.0,3.0,4.0,4.0
131,562,1976,9.0,15.0,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,1.0,2.0,1.0,1.0
132,569,1889,9.0,6.0,1181.0,6309.0,60703,267030,Banua Wuhu,Indonesia,-5,Submarine volcano,NaN,2.0,NaN,NaN
133,578,1711,12.0,11.0,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,3000.0,3.0,3000.0,3000.0
134,580,1812,8.0,6.0,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,953.0,3.0,953.0,953.0
135,581,1856,3.0,2.0,859.0,1995.0,60704,267040,Awu,Indonesia,1318,Stratovolcano,2806.0,3.0,2806.0,2806.0
136,584,1892,6.0,7.0,1197.0,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,1532.0,3.0,1532.0,1532.0
137,585,1913,3.0,14.0,1407.0,2973.0,60704,267040,Awu,Indonesia,1318,Stratovolcano,138.0,2.0,NaN,138.0
138,589,1966,8.0,12.0,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,39.0,4.0,39.0,39.0
140,599,1673,5.0,20.0,312.0,NaN,60804,268040,Gamkonora,Indonesia,1635,Stratovolcano,NaN,5.0,NaN,NaN
141,607,1608,7.0,18.0,222.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,3.0,NaN,NaN
142,617,1772,5.0,9.0,504.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,35.0,3.0,35.0,35.0
143,618,1773,2.0,2.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,2.0,NaN,NaN
145,627,1838,2.0,26.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,4.0,2.0,4.0,4.0
146,629,1840,2.0,2.0,718.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,3.0,NaN,NaN
147,643,1871,8.0,7.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,1.0,2.0,1.0,1.0
148,657,1962,12.0,31.0,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,5.0,2.0,5.0,5.0
150,664,1646,7.0,19.0,5754.0,10519.0,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,NaN,4.0,NaN,NaN
152,666,1861,12.0,29.0,NaN,NaN,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,326.0,4.0,326.0,326.0
153,669,1890,6.0,29.0,NaN,NaN,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,NaN,2.0,NaN,NaN
154,677,1873,1.0,16.0,NaN,NaN,70106,271060,Ragang,Philippines,2790,Stratovolcano,NaN,2.0,NaN,NaN
155,679,1871,4.0,30.0,1020.0,2179.0,70108,271080,Camiguin,Philippines,1552,Stratovolcano,NaN,2.0,NaN,NaN
156,680,1950,9.0,15.0,NaN,NaN,70108,271080,Camiguin,Philippines,1552,Stratovolcano,68.0,3.0,68.0,68.0
157,693,1996,8.0,10.0,NaN,NaN,70202,272020,Kanlaon,Philippines,2435,Stratovolcano,3.0,2.0,3.0,3.0
158,697,1933,12.0,25.0,1666.0,NaN,70301,273010,Bulusan,Philippines,1535,Stratovolcano,9.0,2.0,NaN,9.0
159,698,1978,7.0,29.0,NaN,NaN,70301,273010,Bulusan,Philippines,1535,Stratovolcano,NaN,2.0,NaN,NaN
160,704,1766,7.0,20.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,49.0,3.0,49.0,49.0
161,706,1800,10.0,30.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN,NaN
162,707,1814,2.0,1.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,1200.0,4.0,1200.0,1200.0
163,712,1853,7.0,13.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,34.0,3.0,34.0,34.0
165,716,1871,12.0,8.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,3.0,3.0,3.0,3.0
166,724,1887,3.0,9.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,15.0,3.0,15.0,15.0
167,730,1897,5.0,23.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,350.0,3.0,350.0,350.0
169,733,1938,6.0,5.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN,NaN
170,735,1947,1.0,7.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN,NaN
171,736,1968,4.0,21.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,6.0,3.0,6.0,6.0
172,739,1984,9.0,9.0,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,1.0,3.0,1.0,1.0
174,752,1716,9.0,24.0,387.0,1205.0,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,4.0,NaN,NaN
175,753,1749,8.0,11.0,431.0,1304.0,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,3.0,NaN,NaN
176,754,1754,11.0,28.0,2853.0,1328.0,70307,273070,Taal,Philippines,311,Stratovolcano,12.0,4.0,NaN,12.0
177,756,1874,7.0,19.0,NaN,NaN,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,2.0,NaN,NaN
178,761,1911,1.0,30.0,1392.0,8391.0,70307,273070,Taal,Philippines,311,Stratovolcano,1335.0,3.0,1335.0,1335.0
179,762,1965,9.0,28.0,1977.0,NaN,70307,273070,Taal,Philippines,311,Stratovolcano,355.0,4.0,355.0,355.0
180,777,1969,3.0,21.0,2872.0,NaN,70402,274020,Didicas,Philippines,228,Compound volcano,3.0,2.0,NaN,3.0
181,787,1853,10.0,29.0,809.0,NaN,80103,281030,Unnamed,Taiwan,0,Submarine volcano,NaN,2.0,NaN,NaN
183,823,1933,12.0,24.0,NaN,NaN,80205,282050,Kuchinoerabujima,Japan,657,Stratovolcano,8.0,4.0,8.0,8.0
185,844,766,7.0,20.0,61.0,7341.0,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,3.0,NaN,NaN
186,846,1471,11.0,3.0,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,5.0,NaN,NaN
187,858,1779,11.0,8.0,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,153.0,4.0,153.0,153.0
188,859,1781,4.0,11.0,529.0,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,38.0,4.0,23.0,38.0
189,867,1914,1.0,12.0,1412.0,2994.0,80208,282080,Aira,Japan,1117,Stratovolcano,63.0,4.0,28.0,63.0
191,878,1955,10.0,13.0,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,3.0,NaN,NaN
192,904,1566,10.0,31.0,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,NaN,3.0,NaN,NaN
193,915,1716,11.0,9.0,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,1.0,3.0,1.0,1.0
194,916,1717,2.0,7.0,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,1.0,3.0,1.0,1.0
195,932,1792,5.0,21.0,568.0,1515.0,80210,282100,Unzendake,Japan,1483,Complex volcano,15000.0,2.0,NaN,15000.0
196,933,1991,6.0,3.0,NaN,NaN,80210,282100,Unzendake,Japan,1483,Complex volcano,43.0,1.0,43.0,43.0

#### **TASK 1.3: Tailoring Time (10 Points)**

The year, month, and day columns in the dataset appear to be in an unconventional format. We will need to undertake some fundamental data cleaning on the [time](https://pandas.pydata.org/docs/user_guide/timeseries.html). While more advanced data cleaning techniques will be covered in class, we will focus on basic cleaning for now.

**We need to have only ONE column called** "***date***" **that contains the full date (YYYY-MM-DD), not separated into three columns.**

***Ensure that there are no floating-point values in the date and sort the data from the most recent to the least recent.***

***Remove the old columns and place the new column next to the 'id' column.***


**YOU MAY USE MULTIPLE LINES OF CODE, BUT CAN'T USE LOOPS.**
**Note:** It is alright to have only a **maximum of 12 NaT (Not a Time)s** for some dates that often go further back than the 1600s because the datetime module in Pandas has a limit (unless otherwise guided).

In [61]:
new_df['year'] = new_df['year'].astype(int)
new_df['month'] = new_df['month'].astype(int)
new_df['day'] = new_df['day'].astype(int)
new_df['date'] = pd.to_datetime(new_df[['year', 'month', 'day']],errors='coerce')
new_df = new_df.drop(columns=['year', 'month', 'day'])
new_df = new_df.sort_values('date', ascending=False)
date_column = new_df.pop('date')
new_df.insert(new_df.columns.get_loc('id') + 1, 'date', date_column)

# KEEP THIS. It will display the whole dataframe.
new_df

,id,date,tsunamiEventId,earthquakeEventId,volcanoLocationId,volcanoLocationNewNum,name,country,elevation,morphology,deathsTotal,vei,deaths,totalDeaths
157,693,1996-08-10,NaN,NaN,70202,272020,Kanlaon,Philippines,2435,Stratovolcano,3.0,2.0,3.0,3.0
60,112,1994-11-22,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,60.0,3.0,60.0,60.0
196,933,1991-06-03,NaN,NaN,80210,282100,Unzendake,Japan,1483,Complex volcano,43.0,1.0,43.0,43.0
75,144,1990-02-10,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,32.0,4.0,32.0,32.0
123,486,1988-05-09,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,4.0,3.0,4.0,4.0
31,31,1987-04-17,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,2.0,2.0,2.0,2.0
59,111,1986-10-15,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,1.0,2.0,1.0,1.0
13,13,1986-07-24,NaN,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,1.0,2.0,1.0,1.0
88,203,1985-05-10,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,70.0,3.0,70.0,70.0
172,739,1984-09-09,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,1.0,3.0,1.0,1.0
40,40,1984-08-15,5807.0,NaN,20403,224030,Oku Volcanic Field,Cameroon,3011,Maar,37.0,NaN,37.0,37.0
114,447,1983-08-17,4702.0,NaN,60425,264250,Iliwerung,Indonesia,583,Complex volcano,NaN,1.0,NaN,NaN
124,488,1983-07-23,NaN,NaN,60601,266010,Colo,Indonesia,404,Stratovolcano,NaN,4.0,NaN,NaN
108,398,1981-09-05,NaN,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,NaN,2.0,NaN,NaN
91,206,1981-03-29,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,1.0,3.0,1.0,1.0
30,30,1979-07-05,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,9.0,2.0,9.0,9.0
20,20,1979-03-08,NaN,NaN,50103,251030,Karkar,Papua New Guinea,1839,Stratovolcano,2.0,2.0,2.0,2.0
46,49,1979-02-20,NaN,NaN,60320,263200,Dieng Volcanic Complex,Indonesia,2565,Complex volcano,149.0,1.0,149.0,149.0
89,204,1978-09-19,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,12.0,3.0,12.0,12.0
159,698,1978-07-29,NaN,NaN,70301,273010,Bulusan,Philippines,1535,Stratovolcano,NaN,2.0,NaN,NaN
7,7,1977-01-10,NaN,NaN,20303,223030,Nyiragongo,"Congo, DRC",3470,Stratovolcano,NaN,1.0,NaN,NaN
131,562,1976-09-15,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,1.0,2.0,1.0,1.0
90,205,1976-08-31,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,119.0,2.0,119.0,119.0
130,561,1974-02-11,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,4.0,3.0,4.0,4.0
22,22,1972-06-09,NaN,NaN,30302,233020,"Fournaise, Piton de la",Reunion,2632,Shield volcano,3.0,2.0,3.0,3.0
21,21,1970-03-02,NaN,NaN,10101,211010,Campi Flegrei,Italy,458,Caldera,3.0,NaN,3.0,3.0
180,777,1969-03-21,2872.0,NaN,70402,274020,Didicas,Philippines,228,Compound volcano,3.0,2.0,NaN,3.0
104,389,1969-01-28,NaN,NaN,60411,264110,Iya,Indonesia,618,Stratovolcano,2.0,3.0,2.0,2.0
58,105,1969-01-07,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,3.0,2.0,3.0,3.0
171,736,1968-04-21,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,6.0,3.0,6.0,6.0
87,202,1967-08-31,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,3.0,3.0,3.0,3.0
138,589,1966-08-12,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,39.0,4.0,39.0,39.0
74,141,1966-04-26,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,215.0,4.0,215.0,215.0
179,762,1965-09-28,1977.0,NaN,70307,273070,Taal,Philippines,311,Stratovolcano,355.0,4.0,355.0,355.0
106,395,1964-01-01,NaN,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,1.0,2.0,1.0,1.0
100,345,1963-09-05,NaN,NaN,60401,264010,Batur,Indonesia,1717,Caldera,2.0,2.0,2.0,2.0
102,353,1963-05-16,NaN,4292.0,60402,264020,Agung,Indonesia,2997,Stratovolcano,120.0,3.0,120.0,120.0
86,201,1963-05-05,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,1.0,2.0,1.0,1.0
101,351,1963-03-18,1942.0,NaN,60402,264020,Agung,Indonesia,2997,Stratovolcano,1028.0,5.0,1028.0,1028.0
148,657,1962-12-31,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,5.0,2.0,5.0,5.0
57,104,1961-05-08,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,6.0,3.0,6.0,6.0
126,525,1958-07-12,NaN,NaN,60611,266110,Mahawu,Indonesia,1299,Stratovolcano,1.0,2.0,1.0,1.0
191,878,1955-10-13,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,3.0,NaN,NaN
38,38,1954-08-03,NaN,NaN,50101,251010,Bam,Papua New Guinea,685,Stratovolcano,25.0,2.0,NaN,25.0
56,100,1953-03-23,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,64.0,3.0,64.0,64.0
73,140,1951-08-31,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,7.0,3.0,7.0,7.0
156,680,1950-09-15,NaN,NaN,70108,271080,Camiguin,Philippines,1552,Stratovolcano,68.0,3.0,68.0,68.0
85,200,1950-08-28,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,6.0,1.0,6.0,6.0
112,441,1948-04-07,NaN,NaN,60425,264250,Iliwerung,Indonesia,583,Complex volcano,NaN,2.0,NaN,NaN
170,735,1947-01-07,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN,NaN
84,199,1946-10-29,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN,NaN
45,45,1944-12-04,NaN,NaN,60320,263200,Dieng Volcanic Complex,Indonesia,2565,Complex volcano,117.0,2.0,117.0,117.0
39,39,1944-03-27,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,27.0,2.0,27.0,27.0
82,196,1941-09-21,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN,NaN
129,552,1940-06-20,NaN,NaN,60702,267020,Karangetang,Indonesia,1797,Stratovolcano,1.0,2.0,1.0,1.0
169,733,1938-06-05,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN,NaN
158,697,1933-12-25,1666.0,NaN,70301,273010,Bulusan,Philippines,1535,Stratovolcano,9.0,2.0,NaN,9.0
183,823,1933-12-24,NaN,NaN,80205,282050,Kuchinoerabujima,Japan,657,Stratovolcano,8.0,4.0,8.0,8.0
55,94,1930-12-18,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,1369.0,3.0,1369.0,1369.0
26,26,1930-09-11,4218.0,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,6.0,3.0,5.0,6.0
28,28,1928-11-02,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,5.0,1.0,5.0,5.0
105,394,1928-08-04,1607.0,NaN,60415,264150,Paluweh,Indonesia,875,Stratovolcano,226.0,3.0,98.0,226.0
42,42,1928-01-23,NaN,NaN,10204,212040,Santorini,Greece,367,Shield volcano,48.0,2.0,48.0,48.0
54,92,1920-07-25,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,33.0,3.0,33.0,33.0
25,25,1919-05-22,1476.0,NaN,10104,211040,Stromboli,Italy,924,Stratovolcano,4.0,3.0,4.0,4.0
72,138,1919-05-19,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,5110.0,4.0,5110.0,5110.0
18,18,1917-04-01,NaN,NaN,40105,241050,Okataina,New Zealand,1111,Lava dome,2.0,1.0,2.0,2.0
32,32,1914-09-10,NaN,NaN,40104,241040,Whakaari/White Island,New Zealand,294,Stratovolcano,11.0,NaN,11.0,11.0
189,867,1914-01-12,1412.0,2994.0,80208,282080,Aira,Japan,1117,Stratovolcano,63.0,4.0,28.0,63.0
81,195,1913-06-23,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN,NaN
137,585,1913-03-14,1407.0,2973.0,60704,267040,Awu,Indonesia,1318,Stratovolcano,138.0,2.0,NaN,138.0
34,34,1912-12-03,NaN,NaN,20302,223020,Nyamulagira,"Congo, DRC",3058,Shield volcano,20.0,3.0,20.0,20.0
80,193,1911-11-08,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,3.0,NaN,NaN
178,761,1911-01-30,1392.0,8391.0,70307,273070,Taal,Philippines,311,Stratovolcano,1335.0,3.0,1335.0,1335.0
110,411,1907-09-28,NaN,NaN,60418,264180,Lewotobi,Indonesia,1703,Stratovolcano,1.0,2.0,1.0,1.0
11,11,1907-08-04,NaN,NaN,201112,221112,Alayta,Ethiopia,1496,Shield volcano,NaN,2.0,NaN,NaN
12,12,1905-03-10,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,1.0,2.0,1.0,1.0
15,15,1904-02-25,NaN,NaN,30301,233010,Karthala,Comoros,2361,Shield volcano,1.0,2.0,1.0,1.0
27,27,1903-08-30,NaN,NaN,40105,241050,Okataina,New Zealand,1111,Lava dome,4.0,1.0,4.0,4.0
71,137,1901-05-22,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN,NaN
167,730,1897-05-23,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,350.0,3.0,350.0,350.0
35,35,1895-06-17,NaN,NaN,50103,251030,Karkar,Papua New Guinea,1839,Stratovolcano,21.0,2.0,1.0,21.0
78,176,1895-05-22,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,NaN,2.0,NaN,NaN
136,584,1892-06-07,1197.0,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,1532.0,3.0,1532.0,1532.0
153,669,1890-06-29,NaN,NaN,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,NaN,2.0,NaN,NaN
132,569,1889-09-06,1181.0,6309.0,60703,267030,Banua Wuhu,Indonesia,-5,Submarine volcano,NaN,2.0,NaN,NaN
4,4,1888-03-13,1175.0,NaN,50107,251070,Ritter Island,Papua New Guinea,75,Stratovolcano,NaN,2.0,NaN,NaN
166,724,1887-03-09,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,15.0,3.0,15.0,15.0
33,33,1886-08-31,NaN,NaN,40311,243110,Niuafo'ou,Tonga,260,Shield volcano,NaN,4.0,NaN,NaN
77,167,1885-04-18,NaN,NaN,60330,263300,Semeru,Indonesia,3657,Stratovolcano,74.0,2.0,74.0,74.0
70,136,1875-01-29,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,0.0,NaN,NaN
177,756,1874-07-19,NaN,NaN,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,2.0,NaN,NaN
154,677,1873-01-16,NaN,NaN,70106,271060,Ragang,Philippines,2790,Stratovolcano,NaN,2.0,NaN,NaN
52,82,1872-11-03,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,200.0,4.0,200.0,200.0
29,29,1872-04-24,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,9.0,3.0,9.0,9.0
51,81,1872-04-15,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,30.0,4.0,30.0,30.0
165,716,1871-12-08,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,3.0,3.0,3.0,3.0
147,643,1871-08-07,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,1.0,2.0,1.0,1.0
155,679,1871-04-30,1020.0,2179.0,70108,271080,Camiguin,Philippines,1552,Stratovolcano,NaN,2.0,NaN,NaN
128,533,1871-03-03,1022.0,NaN,60701,267010,Ruang,Indonesia,725,Stratovolcano,400.0,2.0,NaN,400.0
109,410,1869-07-07,NaN,NaN,60418,264180,Lewotobi,Indonesia,1703,Stratovolcano,2.0,2.0,2.0,2.0
69,135,1864-01-03,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,54.0,2.0,54.0,54.0
152,666,1861-12-29,NaN,NaN,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,326.0,4.0,326.0,326.0
135,581,1856-03-02,859.0,1995.0,60704,267040,Awu,Indonesia,1318,Stratovolcano,2806.0,3.0,2806.0,2806.0
181,787,1853-10-29,809.0,NaN,80103,281030,Unnamed,Taiwan,0,Submarine volcano,NaN,2.0,NaN,NaN
163,712,1853-07-13,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,34.0,3.0,34.0,34.0
37,37,1853-06-24,NaN,NaN,40311,243110,Niuafo'ou,Tonga,260,Shield volcano,25.0,0.0,25.0,25.0
68,133,1848-05-16,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,21.0,2.0,21.0,21.0
125,489,1845-02-08,741.0,1865.0,60603,266030,Soputan,Indonesia,1785,Stratovolcano,118.0,2.0,NaN,118.0
44,44,1843-11-17,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,56.0,2.0,56.0,56.0
146,629,1840-02-02,718.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,3.0,NaN,NaN
145,627,1838-02-26,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,4.0,2.0,4.0,4.0
50,71,1832-12-25,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,32.0,3.0,32.0,32.0
6,6,1832-11-01,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,NaN,2.0,NaN,NaN
67,132,1826-10-11,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,3.0,NaN,NaN
49,69,1822-12-27,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,100.0,3.0,100.0,100.0
122,482,1820-06-11,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,NaN,2.0,NaN,NaN
99,333,1817-01-24,NaN,NaN,60335,263350,Ijen,Indonesia,2769,Stratovolcano,NaN,2.0,NaN,NaN
103,367,1815-04-10,613.0,NaN,60404,264040,Tambora,Indonesia,2850,Stratovolcano,60000.0,7.0,11000.0,60000.0
162,707,1814-02-01,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,1200.0,4.0,1200.0,1200.0
134,580,1812-08-06,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,953.0,3.0,953.0,953.0
24,24,1805-08-11,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,4.0,2.0,4.0,4.0
161,706,1800-10-30,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,NaN,2.0,NaN,NaN
195,932,1792-05-21,568.0,1515.0,80210,282100,Unzendake,Japan,1483,Complex volcano,15000.0,2.0,NaN,15000.0
188,859,1781-04-11,529.0,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,38.0,4.0,23.0,38.0
187,858,1779-11-08,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,153.0,4.0,153.0,153.0
9,9,1779-08-08,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,NaN,2.0,NaN,NaN
143,618,1773-02-02,NaN,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,2.0,NaN,NaN
142,617,1772-05-09,504.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,35.0,3.0,35.0,35.0
160,704,1766-07-20,NaN,NaN,70303,273030,Mayon,Philippines,2462,Stratovolcano,49.0,3.0,49.0,49.0
176,754,1754-11-28,2853.0,1328.0,70307,273070,Taal,Philippines,311,Stratovolcano,12.0,4.0,NaN,12.0
175,753,1749-08-11,431.0,1304.0,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,3.0,NaN,NaN
17,17,1737-05-20,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,2.0,2.0,2.0,2.0
194,916,1717-02-07,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,1.0,3.0,1.0,1.0
193,915,1716-11-09,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,1.0,3.0,1.0,1.0
174,752,1716-09-24,387.0,1205.0,70307,273070,Taal,Philippines,311,Stratovolcano,NaN,4.0,NaN,NaN
66,128,1716-07-20,NaN,NaN,60328,263280,Kelud,Indonesia,1730,Stratovolcano,NaN,2.0,NaN,NaN
133,578,1711-12-11,NaN,NaN,60704,267040,Awu,Indonesia,1318,Stratovolcano,3000.0,3.0,3000.0,3000.0
121,477,1694-11-20,NaN,NaN,60509,265090,Banda Api,Pacific Ocean,596,Caldera,NaN,3.0,NaN,NaN
118,466,1692-06-04,NaN,NaN,60507,265070,Serua,Pacific Ocean,608,Stratovolcano,NaN,4.0,NaN,NaN
23,23,1682-08-12,NaN,NaN,10102,211020,Vesuvius,Italy,1281,Complex volcano,4.0,3.0,4.0,4.0
1,1,NaT,2852.0,421.0,10106,211060,Etna,Italy,3357,Stratovolcano,16000.0,NaN,NaN,16000.0
14,14,NaT,NaN,NaN,10106,211060,Etna,Italy,3357,Stratovolcano,1.0,3.0,1.0,1.0
36,36,NaT,NaN,NaN,10101,211010,Campi Flegrei,Italy,458,Caldera,24.0,3.0,24.0,24.0
43,43,NaT,NaN,920.0,201141,221141,Dama Ali,Ethiopia,1068,Shield volcano,50.0,NaN,50.0,50.0
48,64,NaT,NaN,NaN,60325,263250,Merapi,Indonesia,2910,Stratovolcano,3000.0,3.0,3000.0,3000.0
116,457,NaT,285.0,NaN,60505,265050,Teon,Pacific Ocean,728,Stratovolcano,NaN,4.0,NaN,NaN
140,599,NaT,312.0,NaN,60804,268040,Gamkonora,Indonesia,1635,Stratovolcano,NaN,5.0,NaN,NaN
141,607,NaT,222.0,NaN,60806,268060,Gamalama,Indonesia,1715,Stratovolcano,NaN,3.0,NaN,NaN
150,664,NaT,5754.0,10519.0,60807,268070,Kie Besi,Indonesia,1357,Stratovolcano,NaN,4.0,NaN,NaN
185,844,NaT,61.0,7341.0,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,3.0,NaN,NaN
186,846,NaT,NaN,NaN,80208,282080,Aira,Japan,1117,Stratovolcano,NaN,5.0,NaN,NaN
192,904,NaT,NaN,NaN,80209,282090,Kirishimayama,Japan,1700,Shield volcano,NaN,3.0,NaN,NaN

### **Part 2: Volcanic Matryoshkas  (20 POINTS TOTAL)**

Now, that most of the data has been tidied up. We will organize the data into more sizable pieces of information in order to extract useful information.

**2.1.1:** *(5 points here)*

**Use the groupby function in Pandas to create separate dataframes for each unique country.**

* Each table must only have the columns: 'date' 'country', 'name', and 'vei'

* Sort the dataframe of each country by highest to lowest 'vei'

**You MUST use the groupby function here.**

In [ ]:
# REMOVE THIS COMMENT AND ANSWER STARTING HERE

**2.1.2:** *(5 points here)*

**Using groupby again, print out the maximum 'vei' for each unique country.**

**You MUST use the groupby function here.**

* Print out your results in a format like the following: "Country: {country_name}, Highest VEI: {vei}"

In [ ]:
# REMOVE THIS COMMENT AND ANSWER STARTING HERE

**2.1.3:** *(10 points here)*

Finally, we have ALMOST REACHED THE END!!
Since there is still quite a bit of missing data, we want to make use of what is still available.

A very powerful tool in Python's magnificent collection of libraries is its beautiful graphing tools.

Check out libraries such as [Seaborn](https://seaborn.pydata.org/) or [Matplotlib](https://matplotlib.org/stable/index.html) to create meaningful visualizations! **Your final task requires the use of these libraries**

**Based on the unique names of volcanos, filter names that have more than 3 datapoints under their name.**

* Make separate graphs for each volcano and plot their VEIs over time.

* Make sure to properly label all parts of the graph.

In [ ]:
# REMOVE THIS COMMENT AND ANSWER STARTING HERE

### **Part 3: Fiery Jobs  (15 POINTS TOTAL)**

Proficiency in SQL is also super important. SQL databases are essentially relational databases in which there are vast amounts of tabular data. which can often be used to connect with related tablular data. [This](https://www.w3schools.com/sql/) is a pretty good intro into learning more about SQL.

Check out this [tutorial](https://mode.com/sql-tutorial/introduction-to-sql/) for some clarifications on SQL.

Now! We'll be using **sqlite** to access a database.
* Start by downloading the sql lite file and putting it in the same directory as this [notebook](https://www.kaggle.com/datasets/kaggle/sf-salaries) (hit the 'download' button in the upper right).
* Check out the description of the data so you know the table / column names.

The following code will use sqlite3 to create a database connection. sqlite3 is the library in Python that assists in navigating through SQL databases.

In [ ]:
import sqlite3
# import pandas as pd. Pandas was already imported from the previous sections

conn = sqlite3.connect("database.sqlite")
crsr = conn.cursor()

In [ ]:
# This code will let you check out the different tables within the database.
query = "SELECT name FROM sqlite_master WHERE type='table';"
tables = crsr.execute(query).fetchall()
print(tables)

[('Salaries',)]

##### **Remember that each problem should be solved with a single sql query.**
**All outputs must be shown**

#### **3.1.1: 2 Points**
***From the Salaries table, get the average base pay for "firefighters" (all job titles consisting of the word "firefighter" (not case sensitive)) between the year 2011 to 2013.***

In [ ]:
query = 'REMOVE THIS CONTENT AND ANSWER IN HERE'

# KEEP THIS. It will display the whole dataframe.
df = pd.read_sql(query, conn)
df

#### **3.1.2: 2 Points**
***From the Salaries table, create a table for the year 2014, with a job title of "firefighters" (all job titles consisting of the word "firefighter" (not case sensitive)) making under $100,000 as a base pay, and sort in descending order by salary.***

In [ ]:
query = 'REMOVE THIS CONTENT AND ANSWER IN HERE'

# KEEP THIS. It will display the whole dataframe.
df = pd.read_sql(query, conn)
df

#### **3.1.3: 4 Points**
***Create a dataframe with averages of base pay, averages of benefits, and averages of overtime for "firefighters" (all job titles consisting of the word "firefighter" (not case sensitive)) as well as a column with the sum of these three values.***

***Exclude job titles containing "FIREFIGHTER" (case-sensitive)***

In [ ]:
query = 'REMOVE THIS CONTENT AND ANSWER IN HERE'

# KEEP THIS. It will display the whole dataframe.
df = pd.read_sql(query, conn)
df

#### **3.1.4: 7 Points**

***Finally, we'll create our own table in our database. Separate the Salaries table by years, and add it back to the database. Using a loop might be helpful.***

* You may use basic python to complete the task. However, using querying on SQL is **mandatory**.
* Feel free to **use multiple lines of code for this problem only.**
* Check out this [Hint](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html)

In [ ]:
# REMOVE THIS CONTENT AND ANSWER IN YOUR OWN WAY

In [ ]:
# Run this code to check if you successfully added your table.
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('Salaries',)]

![volcano](https://as1.ftcdn.net/v2/jpg/06/34/76/64/1000_F_634766457_0fZbpYj6aBLlldO1jADUPpKTRLnNmngs.jpg)

### **Part 4: Be Creative with SQL  (20 POINTS TOTAL)**

For a more interactive SQL experience within a Jupyter notebook or Google Colab, you can use the %sql magic command from the ipython-sql extension. Here's how:

* Install ipython-sql: !pip install ipython-sql
* Load the extension and connect to SQLite:

%load_ext sql

%sql sqlite:///restaurent.db


* Run SQL queries directly in cells using

%%sql

However, you can also continue to import the sqlite3 library and create a connection and cursor to execute SQL commands, as you did before. The choice is up to you.

*** Part 4.1(a)  CREATE A TABLE ***

Create a table called **MyRestaurants** with the following attributes:

* RestaurantName: A VARCHAR field
* FoodType: A VARCHAR field
* DistanceFromHome: An INTEGER field representing the distance (in minutes) from your house
* LastVisitDate: A DATE field representing the date of your last visit
* Liked: A BOOLEAN field indicating whether you like the restaurant or not

*** Part 4.1(b) Insert Tuples ***

Insert at least five tuples using the SQL INSERT command, executing it five (or more) times.

* Ensure that you insert ** at least one restaurant that you liked**, **at least one restaurant that you did not like**, and **at least one restaurant where the Liked field is set to NULL**.

*** Part 4.1(c) ***

Write a SQL query to return all restaurants in your table.

*** Part 4.1(d) ***

Now experiment with a few of SQLite's output formats using the SQL query you wrote for question above:

* print the results (Part 4.1(c)) in list form, delimited by " | "

Sample output: Sushi Place | Japanese | 15 | 2024-05-01 | 1

*** Part 4.1(d) ***

Modify your SQL query such that it prints "I liked it" or "I hated it" for each restaurant you liked or not.


Note that you are not allowed to modify the table on disk. You should be able to answer this question using only a SELECT statement. A solution that creates and uses an extra table, howerver, will be accepted.

Check: https://www.sqlitetutorial.net/sqlite-case/

*** Part 4.1(e) ***

Write a SQL query to return all restaurants that you like but have not visited in the past three months.

*** Part 4.2(a) ***

** Next we will focus on INNER JOIN **

Let's add a second table called **"RestaurantReviews"** and demonstrate how to perform an inner join between MyRestaurants and RestaurantReviews.

Create the RestaurantReviews Table
First, we'll create the RestaurantReviews table with the following attributes:

* RestaurantName (to match the Name in MyRestaurants)
* ReviewText (text of the review)
* Rating (integer rating)

*** Part 4.2(b) ***

Insert Data into RestaurantReviews
Insert some sample data (at least 5) into this table:

*** Part 4.2(c) Inner Join Query ***
Now perform an inner join between MyRestaurants and RestaurantReviews based on the restaurant name to combine the information from both tables and show the results.

## THE END OF HW 1 ##